/* Chapter 2 — The Human Being (Stage 2, Lessons 2.1–2.4)
   en = NIV (user-supplied). ko/zh/es added — teaching text translated; verses:
   zh = 和合本 (CUV, public domain), es = RVR1909 (public domain), ko = faithful
   working translation (not 개역개정, swappable). */
window.CHAPTER = {
"id":"step-2",
"verses":{
 "gen1_27":{"ref":{"en":"Genesis 1:27","ko":"창세기 1:27","zh":"创世记 1:27","es":"Génesis 1:27"},"t":{"en":"So God created mankind in his own image, in the image of God he created them; male and female he created them.","ko":"그리하여 하나님께서 자기 형상대로 사람을 창조하시되, 하나님의 형상대로 그들을 창조하셨으니, 남자와 여자로 그들을 창조하셨다.","zh":"神就照着自己的形像造人,乃是照着他的形像造男造女。","es":"Y crió Dios al hombre á su imagen, á imagen de Dios lo crió; varón y hembra los crió."}},
 "gen2_7":{"ref":{"en":"Genesis 2:7","ko":"창세기 2:7","zh":"创世记 2:7","es":"Génesis 2:7"},"t":{"en":"Then the LORD God formed a man from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being.","ko":"그때 여호와 하나님께서 땅의 흙으로 사람을 지으시고 그 코에 생명의 숨을 불어넣으시니, 사람이 생령이 되었다.","zh":"耶和华神用地上的尘土造人,将生气吹在他鼻孔里,他就成了有灵的活人,名叫亚当。","es":"Formó, pues, Jehová Dios al hombre del polvo de la tierra, y alentó en su nariz soplo de vida; y fué el hombre en alma viviente."}},
 "rom8_5":{"ref":{"en":"Romans 8:5","ko":"로마서 8:5","zh":"罗马书 8:5","es":"Romanos 8:5"},"t":{"en":"Those who live according to the flesh have their minds set on what the flesh desires; but those who live in accordance with the Spirit have their minds set on what the Spirit desires.","ko":"육신을 따라 사는 자들은 육신이 바라는 것에 마음을 두지만, 영을 따라 사는 자들은 영이 바라는 것에 마음을 둔다.","zh":"因为随从肉体的人体贴肉体的事,随从圣灵的人体贴圣灵的事。","es":"Porque los que viven conforme á la carne, de las cosas que son de la carne se ocupan; mas los que conforme al espíritu, de las cosas del espíritu."}},
 "2co4_16":{"ref":{"en":"2 Corinthians 4:16","ko":"고린도후서 4:16","zh":"哥林多后书 4:16","es":"2 Corintios 4:16"},"t":{"en":"Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day.","ko":"그러므로 우리는 낙심하지 않는다. 비록 우리의 겉사람은 낡아 가지만, 속사람은 날마다 새로워진다.","zh":"所以我们不丧胆。外体虽然毁坏,内心却一天新似一天。","es":"Por tanto, no desmayamos: antes aunque este nuestro hombre exterior se va desgastando, el interior empero se renueva de día en día."}},
 "1th5_23":{"ref":{"en":"1 Thessalonians 5:23","ko":"데살로니가전서 5:23","zh":"帖撒罗尼迦前书 5:23","es":"1 Tesalonicenses 5:23"},"t":{"en":"May God himself, the God of peace, sanctify you through and through. May your whole spirit, soul and body be kept blameless at the coming of our Lord Jesus Christ.","ko":"평강의 하나님께서 친히 여러분을 온전히 거룩하게 하시고, 여러분의 영과 혼과 몸이 우리 주 예수 그리스도께서 오실 때에 흠 없이 지켜지기를 바란다.","zh":"愿赐平安的神亲自使你们全然成圣!又愿你们的灵与魂与身子得蒙保守,在我主耶稣基督降临的时候,完全无可指摘!","es":"Y el Dios de paz os santifique en todo; para que vuestro espíritu y alma y cuerpo sea guardado entero sin reprensión para la venida de nuestro Señor Jesucristo."}},
 "mt4_4":{"ref":{"en":"Matthew 4:4","ko":"마태복음 4:4","zh":"马太福音 4:4","es":"Mateo 4:4"},"t":{"en":"Jesus answered, “It is written: ‘Man shall not live on bread alone, but on every word that comes from the mouth of God.’”","ko":"예수께서 대답하여 이르셨다. “기록되기를 ‘사람이 떡으로만 살 것이 아니요, 하나님의 입에서 나오는 모든 말씀으로 살 것이다’ 하였다.”","zh":"耶稣却回答说:“经上记着说:‘人活着,不是单靠食物,乃是靠神口里所出的一切话。’”","es":"Mas él respondiendo, dijo: Escrito está: No con solo el pan vivirá el hombre, mas con toda palabra que sale de la boca de Dios."}},
 "job7_7":{"ref":{"en":"Job 7:7","ko":"욥기 7:7","zh":"约伯记 7:7","es":"Job 7:7"},"t":{"en":"Remember, O God, that my life is but a breath; my eyes will never see happiness again.","ko":"하나님이여, 기억하소서. 내 생명은 한낱 숨결에 지나지 않으니, 내 눈은 다시는 행복을 보지 못할 것입니다.","zh":"求你想念,我的生命不过是一口气;我的眼睛必不再见福乐。","es":"Acuérdate que mi vida es viento, Y que mis ojos no volverán á ver el bien."}},
 "ps146_3":{"ref":{"en":"Psalm 146:3–4","ko":"시편 146:3–4","zh":"诗篇 146:3–4","es":"Salmo 146:3–4"},"t":{"en":"Do not put your trust in princes, in human beings, who cannot save. When their spirit departs, they return to the ground; on that very day their plans come to nothing.","ko":"너희는 고관들을 의지하지 말고, 구원하지 못하는 인생을 의지하지 말라. 그 영이 떠나면 그는 흙으로 돌아가고, 바로 그날에 그의 계획이 다 사라진다.","zh":"你们不要倚靠君王,不要倚靠世人;他一点不能帮助。他的气一断,就归回尘土;他所打算的,当日就消灭了。","es":"No confiéis en los príncipes, Ni en hijo de hombre, porque no hay en él salud. Saldrá su espíritu, tornaráse en su tierra: En aquel día perecerán sus pensamientos."}},
 "jn1_4":{"ref":{"en":"John 1:4","ko":"요한복음 1:4","zh":"约翰福音 1:4","es":"Juan 1:4"},"t":{"en":"In him was life, and that life was the light of all mankind.","ko":"그 안에 생명이 있었으니, 이 생명은 모든 사람의 빛이었다.","zh":"生命在他里头,这生命就是人的光。","es":"En él estaba la vida, y la vida era la luz de los hombres."}},
 "jn6_63":{"ref":{"en":"John 6:63","ko":"요한복음 6:63","zh":"约翰福音 6:63","es":"Juan 6:63"},"t":{"en":"The Spirit gives life; the flesh counts for nothing. The words I have spoken to you—they are full of the Spirit and life.","ko":"살리는 것은 영이니, 육신은 아무 유익이 없다. 내가 너희에게 이른 말은 영이요 생명이다.","zh":"叫人活着的乃是灵,肉体是无益的。我对你们所说的话就是灵,就是生命。","es":"El espíritu es el que da vida; la carne nada aprovecha: las palabras que yo os he hablado, son espíritu y son vida."}},
 "jn15_7":{"ref":{"en":"John 15:7","ko":"요한복음 15:7","zh":"约翰福音 15:7","es":"Juan 15:7"},"t":{"en":"If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you.","ko":"너희가 내 안에 거하고 내 말이 너희 안에 거하면, 무엇이든 원하는 것을 구하라. 그리하면 너희에게 이루어질 것이다.","zh":"你们若常在我里面,我的话也常在你们里面,凡你们所愿意的,祈求,就给你们成就。","es":"Si estuviereis en mí, y mis palabras estuvieren en vosotros, pedid todo lo que quisiereis, y os será hecho."}},
 "jn12_50":{"ref":{"en":"John 12:50","ko":"요한복음 12:50","zh":"约翰福音 12:50","es":"Juan 12:50"},"t":{"en":"I know that his command leads to eternal life. So whatever I say is just what the Father has told me to say.","ko":"나는 그분의 계명이 곧 영생에 이르게 하는 줄 안다. 그러므로 내가 말하는 것은 바로 아버지께서 내게 말씀하신 그대로이다.","zh":"我也知道他的命令就是永生。故此,我所讲的话正是照着父对我所说的。","es":"Y sé que su mandamiento es vida eterna: así que, lo que yo hablo, como el Padre me lo ha dicho, así hablo."}},
 "lk16_22":{"ref":{"en":"Luke 16:22–23","ko":"누가복음 16:22–23","zh":"路加福音 16:22–23","es":"Lucas 16:22–23"},"t":{"en":"The time came when the beggar died and the angels carried him to Abraham’s side. The rich man also died and was buried. In Hades, where he was in torment, he looked up and saw Abraham far away, with Lazarus by his side.","ko":"이윽고 그 거지가 죽어 천사들에게 이끌려 아브라함의 품으로 갔다. 그 부자도 죽어 장사되었다. 그가 음부에서 고통 받는 중에 눈을 들어 멀리 아브라함과 그 품에 있는 나사로를 바라보았다.","zh":"后来那讨饭的死了,被天使带去放在亚伯拉罕的怀里。财主也死了,并且埋葬了。他在阴间受痛苦,举目远远地望见亚伯拉罕,又望见拉撒路在他怀里。","es":"Y aconteció que murió el mendigo, y fué llevado por los ángeles al seno de Abraham: y murió también el rico, y fué sepultado. Y en el infierno alzó sus ojos, estando en los tormentos, y vió á Abraham de lejos, y á Lázaro en su seno."}},
 "1co15_20":{"ref":{"en":"1 Corinthians 15:20","ko":"고린도전서 15:20","zh":"哥林多前书 15:20","es":"1 Corintios 15:20"},"t":{"en":"But Christ has indeed been raised from the dead, the firstfruits of those who have fallen asleep.","ko":"그러나 이제 그리스도께서는 죽은 자들 가운데서 다시 살아나사, 잠든 자들의 첫 열매가 되셨다.","zh":"但基督已经从死里复活,成为睡了之人初熟的果子。","es":"Mas ahora Cristo ha resucitado de los muertos: primicias de los que durmieron es hecho."}},
 "jn5_29":{"ref":{"en":"John 5:29","ko":"요한복음 5:29","zh":"约翰福音 5:29","es":"Juan 5:29"},"t":{"en":"and come out—those who have done what is good will rise to live, and those who have done what is evil will rise to be condemned.","ko":"그리고 나오되, 선을 행한 자들은 부활하여 생명에 이르고, 악을 행한 자들은 부활하여 심판에 이를 것이다.","zh":"就出来;行善的,复活得生;作恶的,复活定罪。","es":"Y los que hicieron bien, saldrán á resurrección de vida; mas los que hicieron mal, á resurrección de condenación."}},
 "ac24_15":{"ref":{"en":"Acts 24:15","ko":"사도행전 24:15","zh":"使徒行传 24:15","es":"Hechos 24:15"},"t":{"en":"and I have the same hope in God as these men themselves have, that there will be a resurrection of both the righteous and the wicked.","ko":"또한 나는 이 사람들 자신도 품고 있는 것과 같은 소망을 하나님 안에서 가지고 있으니, 곧 의인과 악인이 다 부활하리라는 것입니다.","zh":"并且靠着神,盼望死人,无论善恶,都要复活,就是他们自己也有这个盼望。","es":"Teniendo esperanza en Dios que ha de haber resurrección de los muertos, así de justos como de injustos, la cual también ellos esperan."}},
 "2ti4_1":{"ref":{"en":"2 Timothy 4:1","ko":"디모데후서 4:1","zh":"提摩太后书 4:1","es":"2 Timoteo 4:1"},"t":{"en":"In the presence of God and of Christ Jesus, who will judge the living and the dead, and in view of his appearing and his kingdom, I give you this charge:","ko":"하나님 앞과, 산 자와 죽은 자를 심판하실 그리스도 예수 앞에서, 그분의 나타나심과 그분의 나라를 두고 내가 그대에게 엄히 명한다.","zh":"我在神面前,并在将来审判活人死人的基督耶稣面前,凭着他的显现和他的国度嘱咐你:","es":"Requiero yo pues delante de Dios, y del Señor Jesucristo, que ha de juzgar á los vivos y los muertos en su manifestación y en su reino."}},
 "mk9_43":{"ref":{"en":"Mark 9:43–49","ko":"마가복음 9:43–49","zh":"马可福音 9:43–49","es":"Marcos 9:43–49"},"t":{"en":"If your hand causes you to stumble, cut it off. It is better for you to enter life maimed than with two hands to go into hell, where the fire never goes out. And if your foot causes you to stumble, cut it off. It is better for you to enter life crippled than to have two feet and be thrown into hell. And if your eye causes you to stumble, pluck it out. It is better for you to enter the kingdom of God with one eye than to have two eyes and be thrown into hell, where ‘the worms that eat them do not die, and the fire is not quenched.’ Everyone will be salted with fire.","ko":"네 손이 너를 넘어지게 하거든 그것을 찍어 버려라. 두 손을 가지고 꺼지지 않는 불이 타는 지옥에 들어가는 것보다, 불구가 되어 생명에 들어가는 것이 네게 낫다. 그리고 네 발이 너를 넘어지게 하거든 그것을 찍어 버려라. 두 발을 가지고 지옥에 던져지는 것보다, 저는 몸으로 생명에 들어가는 것이 네게 낫다. 그리고 네 눈이 너를 넘어지게 하거든 그것을 빼어 버려라. 두 눈을 가지고 지옥에 던져지는 것보다, 한 눈으로 하나님의 나라에 들어가는 것이 네게 낫다. 거기서는 ‘그들을 갉아먹는 벌레도 죽지 않고, 불도 꺼지지 않는다.’ 각 사람이 불로 소금 치듯 함을 받을 것이다.","zh":"倘若你一只手叫你跌倒,就把它砍下来;你缺了肢体进入永生,强如有两只手落到地狱,入那不灭的火里去。倘若你一只脚叫你跌倒,就把它砍下来;你瘸腿进入永生,强如有两只脚被丢在地狱里。倘若你一只眼叫你跌倒,就去掉它;你只有一只眼进入神的国,强如有两只眼被丢在地狱里。在那里,虫是不死的,火是不灭的。因为必用火当盐腌各人。","es":"Y si tu mano te escandalizare, córtala: mejor te es entrar á la vida manco, que teniendo dos manos ir á la Gehenna, al fuego que no puede ser apagado; y si tu pie te fuere ocasión de caer, córtalo: mejor te es entrar á la vida cojo, que teniendo dos pies ser echado en la Gehenna, al fuego que no puede ser apagado; y si tu ojo te fuere ocasión de caer, sácalo: mejor te es entrar al reino de Dios con un ojo, que teniendo dos ojos ser echado á la Gehenna del fuego; donde el gusano de ellos no muere, y el fuego nunca se apaga. Porque todos serán salados con fuego, y todo sacrificio será salado con sal."}},
 "1co15_23":{"ref":{"en":"1 Corinthians 15:20–23","ko":"고린도전서 15:20–23","zh":"哥林多前书 15:20–23","es":"1 Corintios 15:20–23"},"t":{"en":"But Christ has indeed been raised from the dead, the firstfruits of those who have fallen asleep. For since death came through a man, the resurrection of the dead comes also through a man. For as in Adam all die, so in Christ all will be made alive. But each in turn: Christ, the firstfruits; then, when he comes, those who belong to him.","ko":"그러나 이제 그리스도께서는 죽은 자들 가운데서 다시 살아나사, 잠든 자들의 첫 열매가 되셨다. 사망이 한 사람으로 말미암아 왔으니, 죽은 자의 부활도 한 사람으로 말미암아 온다. 아담 안에서 모든 사람이 죽은 것같이, 그리스도 안에서 모든 사람이 살아날 것이다. 그러나 각 사람이 자기 차례대로 되리니, 첫 열매는 그리스도요, 그다음은 그가 오실 때에 그리스도께 속한 자들이다.","zh":"但基督已经从死里复活,成为睡了之人初熟的果子。死既是因一人而来,死人复活也是因一人而来。在亚当里众人都死了;照样,在基督里众人也都要复活。但各人是按着自己的次序复活:初熟的果子是基督;以后,在他来的时候,是那些属基督的。","es":"Mas ahora Cristo ha resucitado de los muertos: primicias de los que durmieron es hecho. Porque por cuanto la muerte entró por un hombre, también por un hombre la resurrección de los muertos. Porque así como en Adam todos mueren, así también en Cristo todos serán vivificados. Mas cada uno en su orden: Cristo las primicias; luego los que son de Cristo, en su venida."}},
 "rev20_4":{"ref":{"en":"Revelation 20:4–6","ko":"요한계시록 20:4–6","zh":"启示录 20:4–6","es":"Apocalipsis 20:4–6"},"t":{"en":"I saw thrones on which were seated those who had been given authority to judge. And I saw the souls of those who had been beheaded because of their testimony about Jesus and because of the word of God. They had not worshiped the beast or its image and had not received its mark on their foreheads or their hands. They came to life and reigned with Christ a thousand years. (The rest of the dead did not come to life until the thousand years were ended.) This is the first resurrection. Blessed and holy are those who share in the first resurrection. The second death has no power over them, but they will be priests of God and of Christ and will reign with him for a thousand years.","ko":"또 나는 여러 보좌와 그 위에 앉은 이들을 보았는데, 그들에게 심판할 권세가 주어졌다. 또 나는 예수를 증언한 것과 하나님의 말씀 때문에 목 베임을 당한 자들의 혼과, 그 짐승이나 그의 형상에게 경배하지 않고 이마와 손에 그의 표를 받지 않은 자들의 혼을 보았다. 그들이 살아나 그리스도와 함께 천 년 동안 왕 노릇 하였다. (그 나머지 죽은 자들은 천 년이 끝나기까지 살아나지 못하였다.) 이것이 첫째 부활이다. 첫째 부활에 참여하는 자들은 복이 있고 거룩하다. 그들에게는 둘째 사망이 아무 권세를 부리지 못하며, 그들은 하나님과 그리스도의 제사장이 되어 그와 함께 천 년 동안 왕 노릇 할 것이다.","zh":"我又看见几个宝座,也有坐在上面的,并有审判的权柄赐给他们。我又看见那些因为给耶稣作见证,并为神之道被斩者的灵魂,和那没有拜过兽与兽像,也没有在额上和手上受过他印记之人的灵魂,他们都复活了,与基督一同作王一千年。其余的死人还没有复活,直等那一千年完了。这是头一次的复活。在头一次复活有分的有福了,圣洁了!第二次的死在他们身上没有权柄。他们必作神和基督的祭司,并要与基督一同作王一千年。","es":"Y vi tronos, y se sentaron sobre ellos, y les fué dado juicio; y vi las almas de los degollados por el testimonio de Jesús, y por la palabra de Dios, y que no habían adorado la bestia, ni á su imagen, y que no recibieron la señal en sus frentes, ni en sus manos, y vivieron y reinaron con Cristo mil años. Mas los otros muertos no tornaron á vivir hasta que sean cumplidos mil años. Esta es la primera resurrección. Bienaventurado y santo el que tiene parte en la primera resurrección; la segunda muerte no tiene potestad en éstos; antes serán sacerdotes de Dios y de Cristo, y reinarán con él mil años."}}
},
"blocks":[

 {"t":"lesson","n":"2.1","title":{"en":"The True “Me”","ko":"참된 “나”","zh":"真正的“我”","es":"El verdadero “yo”"}},
 {"t":"p","x":{"en":"It is our human nature to want to know about ourselves. Throughout our whole life we search for our identity. Who am I? What am I?","ko":"자신에 대해 알고자 하는 것은 인간의 본성입니다. 우리는 일평생 자신의 정체성을 찾습니다. 나는 누구인가? 나는 무엇인가?","zh":"想要认识自己，是人的天性。我们一生都在寻找自己的身份。我是谁？我是什么？","es":"Es propio de la naturaleza humana querer conocernos a nosotros mismos. A lo largo de toda la vida buscamos nuestra identidad. ¿Quién soy? ¿Qué soy?"}},
 {"t":"p","x":{"en":"This is also the effort of every form of knowledge — philosophy, sociology, biology and so on — as they search and examine who we are and what makes us who we are. We also learn about ourselves through others, through our relationships with them. But can they tell us who we really are? Where we come from? Where we are going?","ko":"이것은 모든 학문 — 철학, 사회학, 생물학 등 — 의 노력이기도 합니다. 그것들은 우리가 누구이며 무엇이 우리를 우리 되게 하는지를 찾고 살핍니다. 우리는 또한 다른 사람들을 통해, 그들과의 관계를 통해 자신에 대해 알아 갑니다. 그러나 그것들이 우리가 참으로 누구인지 말해 줄 수 있습니까? 우리가 어디서 왔는지? 우리가 어디로 가는지?","zh":"这也是一切学问——哲学、社会学、生物学等等——的努力，它们都在寻求并探究我们是谁，是什么使我们成为我们。我们也借着他人、借着与他人的关系来认识自己。然而，它们能告诉我们，我们究竟是谁吗？我们从哪里来？要往哪里去？","es":"Este es también el empeño de todo tipo de conocimiento —la filosofía, la sociología, la biología, etc.—, que buscan y examinan quiénes somos y qué nos hace ser lo que somos. También llegamos a conocernos a través de los demás, mediante nuestra relación con ellos. Pero ¿pueden decirnos quiénes somos en verdad? ¿De dónde venimos? ¿A dónde vamos?"}},

 {"t":"h","x":{"en":"The True “Me” — Who Am I?","ko":"참된 “나” — 나는 누구인가?","zh":"真正的“我”——我是谁？","es":"El verdadero “yo” — ¿Quién soy?"}},
 {"t":"p","x":{"en":"The Bible tells us where we come from and who we are: we are people created in the image of God (Genesis 1:27). Furthermore, it shows us that we are spiritual beings and that we came from God (Genesis 2:7; Luke 3:23–38). So the Bible is like a mirror through which we can discover our true identity.","ko":"성경은 우리가 어디서 왔으며 누구인지를 말해 줍니다. 우리는 하나님의 형상을 따라 지음받은 사람입니다(창세기 1:27). 나아가 성경은 우리가 영적 존재이며 하나님께로부터 왔음을 보여 줍니다(창세기 2:7; 누가복음 3:23–38). 그러므로 성경은 우리가 참된 정체성을 발견할 수 있는 거울과 같습니다.","zh":"圣经告诉我们，我们从哪里来，我们是谁：我们是照着神的形象被造的人（创世记 1:27）。而且，圣经向我们显明，我们是属灵的存在，是从神而来的（创世记 2:7；路加福音 3:23–38）。所以，圣经就像一面镜子，我们可以借着它发现自己真正的身份。","es":"La Biblia nos dice de dónde venimos y quiénes somos: somos personas creadas a imagen de Dios (Génesis 1:27). Más aún, nos muestra que somos seres espirituales y que venimos de Dios (Génesis 2:7; Lucas 3:23–38). Así, la Biblia es como un espejo por medio del cual podemos descubrir nuestra verdadera identidad."}},
 {"t":"s","v":["gen1_27"]},
 {"t":"p","x":{"en":"Importantly, we are made of two parts: the flesh and the spirit. The flesh is the visible part of us, which we know as “me.” But there is another “me,” the invisible part — the spirit. While the flesh lives for a finite time, the spirit lives infinitely. So the flesh is like clothing for the spirit. The spirit is the true “me.”","ko":"중요한 것은, 우리가 두 부분, 곧 육신과 영으로 이루어져 있다는 사실입니다. 육신은 우리의 보이는 부분으로, 우리가 “나”로 아는 것입니다. 그러나 또 다른 “나,” 곧 보이지 않는 부분인 영이 있습니다. 육신은 유한한 시간 동안 살지만, 영은 무한히 삽니다. 그러므로 육신은 영의 옷과 같습니다. 영이야말로 참된 “나”입니다.","zh":"重要的是，我们是由两部分构成的：肉体和灵。肉体是我们看得见的部分，就是我们所认识的“我”。但还有另一个“我”，就是那看不见的部分——灵。肉体只活有限的时间，灵却活到无限。所以肉体就像灵的衣服。灵才是真正的“我”。","es":"Lo importante es que estamos formados por dos partes: la carne y el espíritu. La carne es la parte visible de nosotros, la que conocemos como “yo”. Pero hay otro “yo”, la parte invisible: el espíritu. Mientras que la carne vive por un tiempo limitado, el espíritu vive infinitamente. Así, la carne es como el vestido del espíritu. El espíritu es el verdadero “yo”."}},
 {"t":"twoself"},
 {"t":"q","items":[{"en":"When someone asks you, “Who are you?”, what comes to mind first? Why? But is that really who or what you are?","ko":"누군가 당신에게 “당신은 누구입니까?”라고 물을 때, 가장 먼저 무엇이 떠오릅니까? 왜 그렇습니까? 그러나 그것이 정말로 당신이 누구인지, 혹은 무엇인지를 말해 줍니까?","zh":"当有人问你：“你是谁？”时，你最先想到的是什么？为什么？但那真的就是你是谁、你是什么吗？","es":"Cuando alguien te pregunta: “¿Quién eres?”, ¿qué es lo primero que te viene a la mente? ¿Por qué? Pero ¿es eso realmente quién o qué eres?"}]},

 {"t":"h","x":{"en":"What Am I Made Of?","ko":"나는 무엇으로 이루어져 있는가?","zh":"我是由什么构成的？","es":"¿De qué estoy hecho?"}},
 {"t":"summary","mark":"✳","title":{"en":"The composition of man","ko":"사람의 구성","zh":"人的构成","es":"La composición del ser humano"},"rows":[
   {"k":{"en":"Two beings","ko":"두 존재","zh":"两个存在","es":"dos seres"},"v":{"en":"the flesh + the spirit","ko":"육신 + 영","zh":"肉体 + 灵","es":"la carne + el espíritu"}},
   {"k":{"en":"Three functions","ko":"세 기능","zh":"三个功能","es":"tres funciones"},"v":{"en":"the flesh + the spirit + the person (the “soul”)","ko":"육신 + 영 + 인격(혼)","zh":"肉体 + 灵 + 位格（魂）","es":"la carne + el espíritu + la persona (el alma)"}}
 ]},
 {"t":"s","v":["gen2_7"]},
 {"t":"p","x":{"en":"God formed the man from the dust of the ground and made him in His image. Into such a man God breathed His breath, the breath of life, and the man became a living being — the spiritual being living in the flesh. In other words, the man became Adam, the living being (1 Corinthians 15:45).","ko":"하나님께서 땅의 흙으로 사람을 지으시고 자기 형상대로 그를 만드셨습니다. 그러한 사람에게 하나님께서 자기의 숨, 곧 생명의 기운을 불어넣으시니, 그 사람이 생령 — 육신 안에 사는 영적 존재 — 이 되었습니다. 다시 말해, 그 사람은 아담, 곧 생령이 되었습니다(고린도전서 15:45).","zh":"神用地上的尘土造了人，并照着自己的形象造他。神将自己的气息，就是生命的气息，吹进这样一个人里面，那人就成了有灵的活人——就是住在肉体里的属灵存在。换句话说，那人成了亚当，就是有灵的活人（哥林多前书 15:45）。","es":"Dios formó al hombre del polvo de la tierra y lo hizo a su imagen. En ese hombre Dios sopló su aliento, el aliento de vida, y el hombre llegó a ser un ser viviente — el ser espiritual que vive en la carne. En otras palabras, el hombre llegó a ser Adán, el ser viviente (1 Corintios 15:45)."}},
 {"t":"p","x":{"en":"Thus man is made up of two beings: the flesh and the spirit. A “being,” in this sense, is something that either lives or dies. Both the flesh and the spirit are beings, because each can either live or die.","ko":"이와 같이 사람은 두 존재, 곧 육신과 영으로 이루어져 있습니다. 여기서 “존재”란 살거나 죽거나 하는 것을 뜻합니다. 육신과 영은 둘 다 존재인데, 이는 각각이 살 수도 있고 죽을 수도 있기 때문입니다.","zh":"这样，人是由两个存在构成的：肉体和灵。在这里，所谓“存在”，是指或活或死的东西。肉体和灵都是存在，因为它们各自都能或活或死。","es":"Así, el ser humano está formado por dos seres: la carne y el espíritu. Un “ser”, en este sentido, es algo que vive o muere. Tanto la carne como el espíritu son seres, porque cada uno puede vivir o morir."}},
 {"t":"s","v":["rom8_5","2co4_16"]},
 {"t":"p","x":{"en":"So we are two beings. But besides our flesh and spirit, we have something called “the person” — also called “the soul,” or the personality. The person is not a being but a function, and it is what makes us unique individuals.","ko":"그러므로 우리는 두 존재입니다. 그러나 우리의 육신과 영 외에도, 우리에게는 “인격”이라 불리는 것 — 또한 “혼,” 곧 인격성이라 불리는 것 — 이 있습니다. 인격은 존재가 아니라 기능이며, 우리를 각기 독특한 개인이 되게 하는 것입니다.","zh":"所以我们是两个存在。但除了我们的肉体和灵之外，我们还有一样东西，叫作“位格”——也称为“魂”，或说人格。位格不是一个存在，而是一种功能，正是它使我们成为独特的个体。","es":"Así que somos dos seres. Pero, además de nuestra carne y nuestro espíritu, tenemos algo llamado “la persona” — también llamado “el alma”, o la personalidad. La persona no es un ser, sino una función, y es lo que nos hace individuos únicos."}},
 {"t":"s","v":["1th5_23"]},
 {"t":"human","title":{"en":"The composition of man","ko":"사람의 구성","zh":"人的构成","es":"La composición del ser humano"},"parts":[
   {"role":"living","k":{"en":"A LIVING BEING","ko":"생령","zh":"有灵的活人","es":"UN SER VIVIENTE"},"b":{"en":"The human being","ko":"사람","zh":"人","es":"El ser humano"},"s":{"en":"Dust from the ground and the breath of God, joined in one — the man became a living being.","ko":"땅의 흙과 하나님의 숨이 하나로 합하여 — 그 사람이 생령이 되었습니다.","zh":"地上的尘土与神的气息合而为一——那人就成了有灵的活人。","es":"El polvo de la tierra y el aliento de Dios, unidos en uno — el hombre llegó a ser un ser viviente."},"ev":["gen2_7"]},
   {"role":"flesh","k":{"en":"BEING ONE · VISIBLE","ko":"존재 하나 · 보이는 것","zh":"存在一 · 可见","es":"SER UNO · VISIBLE"},"b":{"en":"The flesh","ko":"육신","zh":"肉体","es":"La carne"},"s":{"en":"The visible “me,” formed from the dust of the ground — real, but temporary; it returns to dust.","ko":"땅의 흙으로 지어진 보이는 “나” — 실재하지만 일시적이며, 흙으로 돌아갑니다.","zh":"那看得见的“我”，是用地上的尘土造成的——真实，却是暂时的；它要归回尘土。","es":"El “yo” visible, formado del polvo de la tierra — real, pero temporal; vuelve al polvo."},"ev":["gen2_7"]},
   {"role":"spirit","k":{"en":"BEING TWO · INVISIBLE","ko":"존재 둘 · 보이지 않는 것","zh":"存在二 · 不可见","es":"SER DOS · INVISIBLE"},"b":{"en":"The spirit","ko":"영","zh":"灵","es":"El espíritu"},"s":{"en":"Unseen, breathed from God, made in his image and infinite — this is the true “me.”","ko":"보이지 않으며, 하나님께로부터 불어넣어졌고, 그분의 형상대로 지어졌으며 무한합니다 — 이것이 참된 “나”입니다.","zh":"看不见，是从神吹入的，照着他的形象被造，且是无限的——这就是真正的“我”。","es":"Invisible, soplado por Dios, hecho a su imagen e infinito — este es el verdadero “yo”."},"ev":["gen1_27"]},
   {"role":"soul","k":{"en":"THE FUNCTION","ko":"기능","zh":"功能","es":"LA FUNCIÓN"},"b":{"en":"The person (the “soul”)","ko":"인격(혼)","zh":"位格（魂）","es":"La persona (el alma)"},"s":{"en":"Not a being but a function — intelligence, emotion and free will; through the flesh in life, the spirit after death.","ko":"존재가 아니라 기능 — 지성, 감정, 자유의지이며, 살아 있는 동안에는 육신을 통하여, 죽은 후에는 영을 통하여 나타납니다.","zh":"不是一个存在，而是一种功能——理智、情感和自由意志；活着时借着肉体，死后借着灵。","es":"No un ser, sino una función — inteligencia, emoción y libre albedrío; a través de la carne en vida, del espíritu después de la muerte."},"ev":["1th5_23"]},
   {"role":"word","k":{"en":"LIFE BY THE WORD","ko":"말씀으로 사는 생명","zh":"借着道而活","es":"VIDA POR LA PALABRA"},"b":{"en":"God → Word → Spirit","ko":"하나님 → 말씀 → 영","zh":"神 → 道 → 灵","es":"Dios → Palabra → Espíritu"},"s":{"en":"Man lives not on bread but on every word from the mouth of God; the Spirit receives it and lives.","ko":"사람은 떡으로 사는 것이 아니라 하나님의 입에서 나오는 모든 말씀으로 삽니다. 영이 그것을 받아 삽니다.","zh":"人活着不是单靠食物，乃是靠神口里所出的一切话；灵领受了它，就活着。","es":"El hombre no vive de pan, sino de toda palabra que sale de la boca de Dios; el espíritu la recibe y vive."},"ev":["mt4_4","jn6_63"]}
 ]},

 {"t":"h","x":{"en":"The Person (the “Soul”)","ko":"인격(혼)","zh":"位格（魂）","es":"La persona (el alma)"}},
 {"t":"p","x":{"en":"When God formed the man from the dust, the person was formed together with his flesh. While the flesh is alive, the person is expressed through the flesh; after the flesh dies, the person is then expressed through the spirit.","ko":"하나님께서 흙으로 사람을 지으실 때, 인격도 그의 육신과 함께 지어졌습니다. 육신이 살아 있는 동안에는 인격이 육신을 통하여 나타나고, 육신이 죽은 후에는 인격이 영을 통하여 나타납니다.","zh":"神用尘土造人的时候，位格也与他的肉体一同被造。肉体活着的时候，位格借着肉体显明出来；肉体死后，位格就借着灵显明出来。","es":"Cuando Dios formó al hombre del polvo, la persona fue formada junto con su carne. Mientras la carne vive, la persona se expresa a través de la carne; cuando la carne muere, la persona se expresa entonces a través del espíritu."}},
 {"t":"p","x":{"en":"The person refers to our intelligence, emotion and free will. Because we have intelligence, we can learn, retain and apply knowledge. Because we have emotion, we can express whether we are happy or sad, angry or afraid. And because we have free will, we can make decisions and plans and follow them through.","ko":"인격은 우리의 지성과 감정과 자유의지를 가리킵니다. 우리에게 지성이 있으므로 우리는 지식을 배우고 간직하며 적용할 수 있습니다. 우리에게 감정이 있으므로 우리는 기쁜지 슬픈지, 화가 나는지 두려운지를 표현할 수 있습니다. 그리고 우리에게 자유의지가 있으므로 우리는 결정과 계획을 세우고 그것을 끝까지 이루어 갈 수 있습니다.","zh":"位格是指我们的理智、情感和自由意志。因为我们有理智，就能学习、记住并运用知识。因为我们有情感，就能表达我们是喜乐还是忧愁，是发怒还是惧怕。又因为我们有自由意志，就能作出决定和计划，并把它们贯彻到底。","es":"La persona se refiere a nuestra inteligencia, emoción y libre albedrío. Porque tenemos inteligencia, podemos aprender, retener y aplicar el conocimiento. Porque tenemos emoción, podemos expresar si estamos alegres o tristes, enojados o temerosos. Y porque tenemos libre albedrío, podemos tomar decisiones y hacer planes y llevarlos a cabo."}},
 {"t":"p","x":{"en":"Moreover, it is through the person that we can receive the word of God into our spirit: we use our intelligence to understand the word, our emotion to express our response to it, and our free will to make the decision to receive and obey it.","ko":"뿐만 아니라, 우리가 하나님의 말씀을 우리의 영 안으로 받아들일 수 있는 것도 인격을 통해서입니다. 우리는 지성으로 말씀을 이해하고, 감정으로 그 말씀에 대한 우리의 반응을 표현하며, 자유의지로 그 말씀을 받아 순종하기로 결정합니다.","zh":"而且，我们能将神的道领受到我们的灵里，也是借着位格：我们用理智去明白这道，用情感去表达我们对它的回应，用自由意志去作出领受并顺从它的决定。","es":"Además, es a través de la persona que podemos recibir la palabra de Dios en nuestro espíritu: usamos nuestra inteligencia para entender la palabra, nuestra emoción para expresar nuestra respuesta a ella, y nuestro libre albedrío para tomar la decisión de recibirla y obedecerla."}},
 {"t":"q","items":[{"en":"What kind of “person” do you have? How do you think it affects the way you understand and follow the word of God?","ko":"당신은 어떤 “인격”을 가지고 있습니까? 그것이 당신이 하나님의 말씀을 이해하고 따르는 방식에 어떻게 영향을 미친다고 생각합니까?","zh":"你拥有怎样的“位格”？你认为它如何影响你理解并遵行神的道的方式？","es":"¿Qué clase de “persona” tienes? ¿Cómo crees que influye en la manera en que entiendes y sigues la palabra de Dios?"}]},

 {"t":"h","x":{"en":"The Living Being & the Word","ko":"생령과 말씀","zh":"有灵的活人与道","es":"El ser viviente y la Palabra"}},
 {"t":"p","x":{"en":"The Bible describes the living being as the spirit that has flesh, and that is formed together with the flesh. So only while the spirit stays in the flesh is the individual called a “living being.” Though it has the function to live forever, it has no ability to live on its own. It can live only by the word of God.","ko":"성경은 생령을 육신을 가진 영, 곧 육신과 함께 지어진 영으로 묘사합니다. 그러므로 영이 육신 안에 머물러 있는 동안에만 그 개인은 “생령”이라 불립니다. 생령은 영원히 살 수 있는 기능을 가지고 있으나, 스스로 살 능력은 없습니다. 오직 하나님의 말씀으로만 살 수 있습니다.","zh":"圣经把有灵的活人描述为拥有肉体的灵，就是与肉体一同被造的灵。所以，唯有当灵还留在肉体里的时候，这个个体才被称为“有灵的活人”。它虽有永远活着的功能，却没有靠自己活着的能力。它只能靠神的道而活。","es":"La Biblia describe al ser viviente como el espíritu que tiene carne, y que es formado junto con la carne. Por eso, solo mientras el espíritu permanece en la carne se llama al individuo “ser viviente”. Aunque tiene la función de vivir para siempre, no tiene la capacidad de vivir por sí mismo. Solo puede vivir por la palabra de Dios."}},
 {"t":"s","v":["mt4_4"]},
 {"t":"p","x":{"en":"This is why God gave Adam the commandment regarding the fruit of the tree of the knowledge of good and evil: “you must not eat” (Genesis 2:17). For the living being to live, Adam had to eat the word and obey the commandment.","ko":"이것이 바로 하나님께서 아담에게 선악을 알게 하는 나무의 열매에 관하여 “먹지 말라”는 계명을 주신 이유입니다(창세기 2:17). 생령이 살기 위해서는, 아담은 말씀을 먹고 그 계명에 순종해야 했습니다.","zh":"这就是为什么神就那分别善恶树上的果子吩咐亚当：“你不可吃”（创世记 2:17）。为使有灵的活人活着，亚当必须吃这道，并顺从这诫命。","es":"Por eso Dios le dio a Adán el mandamiento acerca del fruto del árbol del conocimiento del bien y del mal: “no debes comer” (Génesis 2:17). Para que el ser viviente viviera, Adán debía comer la palabra y obedecer el mandamiento."}},
 {"t":"p","x":{"en":"For the spiritual being to “live” is to have the same life as God — that is, eternal life. And eternal life is living eternally with God and like God: joyfully, happily and gloriously, with Him, forever. For us to have eternal life we must obey the word. The flesh eats to live, yet it still dies; but when the spirit eats the word of God and obeys it, it can live forever with God.","ko":"영적 존재가 “산다”는 것은 하나님과 같은 생명 — 곧 영생 — 을 가지는 것입니다. 그리고 영생은 하나님과 함께, 하나님처럼 영원히 사는 것입니다. 곧 기쁘고 행복하며 영광스럽게, 그분과 함께, 영원히 사는 것입니다. 우리가 영생을 얻으려면 말씀에 순종해야 합니다. 육신은 살기 위해 먹지만 여전히 죽습니다. 그러나 영이 하나님의 말씀을 먹고 그것에 순종하면, 하나님과 함께 영원히 살 수 있습니다.","zh":"属灵的存在“活着”，就是拥有与神一样的生命——也就是永生。而永生，就是与神同在、像神一样地永远活着：喜乐、幸福、荣耀地，与他同在，直到永远。我们要得着永生，就必须顺从这道。肉体吃是为了活着，却仍要死；但灵一吃神的道并顺从它，就能与神永远同活。","es":"Que el ser espiritual “viva” es tener la misma vida que Dios — es decir, la vida eterna. Y la vida eterna es vivir eternamente con Dios y como Dios: con gozo, felicidad y gloria, junto a Él, para siempre. Para tener la vida eterna debemos obedecer la palabra. La carne come para vivir, y aun así muere; pero cuando el espíritu come la palabra de Dios y la obedece, puede vivir para siempre con Dios."}},
 {"t":"summary","title":{"en":"The Word","ko":"말씀","zh":"道","es":"La Palabra"},"rows":[
   {"v":{"en":"the food for the spirit","ko":"영의 양식","zh":"灵的食物","es":"el alimento para el espíritu"}},
   {"v":{"en":"life is in it","ko":"그 안에 생명이 있음","zh":"生命在其中","es":"en ella está la vida"}},
   {"v":{"en":"the connection between God and the living being","ko":"하나님과 생령 사이의 연결","zh":"神与有灵的活人之间的连接","es":"la conexión entre Dios y el ser viviente"}}
 ]},
 {"t":"q","items":[{"en":"Are you eating the word? How are you eating it, and what kind of word? Discuss any challenges you face in obeying the word.","ko":"당신은 말씀을 먹고 있습니까? 어떻게 먹고 있으며, 어떤 말씀을 먹고 있습니까? 말씀에 순종하는 데 있어 겪는 어려움이 있다면 함께 나누어 보십시오.","zh":"你在吃这道吗？你是怎样吃的，吃的是怎样的道？请一同分享你在顺从这道上所遇到的任何难处。","es":"¿Estás comiendo la palabra? ¿Cómo la comes, y qué clase de palabra? Conversen sobre las dificultades que enfrentas para obedecer la palabra."}]},
 {"t":"lesson","n":"2.2","title":{"en":"The Life for the Spirit","ko":"영을 위한 생명","zh":"为灵的生命","es":"La vida para el espíritu"}},
 {"t":"p","x":{"en":"When you hear the word “life,” what do you think of? When God promises us “life,” what kind of life is it? Do we already have such a life in our bodies?","ko":"“생명”이라는 말을 들으면 무엇이 떠오릅니까? 하나님께서 우리에게 “생명”을 약속하실 때, 그것은 어떤 생명입니까? 우리는 이미 그런 생명을 우리 몸 안에 가지고 있습니까?","zh":"当你听到“生命”这个词时，你会想到什么？当神应许我们“生命”时，那是怎样的生命？我们的身体里已经拥有这样的生命了吗？","es":"Cuando escuchas la palabra “vida”, ¿en qué piensas? Cuando Dios nos promete “vida”, ¿qué clase de vida es? ¿Ya tenemos tal vida en nuestro cuerpo?"}},

 {"t":"h","x":{"en":"The “Life” of Man","ko":"사람의 “생명”","zh":"人的“生命”","es":"La “vida” del hombre"}},
 {"t":"p","x":{"en":"The Bible points to the fact that the life of the flesh is in its breath — and that makes our life in the flesh fragile, even pitiful. Indeed, the Bible treats the “life” of man and “breath” as the same (nephesh in the Old Testament, psuchē in the New Testament).","ko":"성경은 육신의 생명이 그 호흡에 있다는 사실을 가리킵니다 — 그래서 육신 안에 있는 우리의 생명은 연약하며, 심지어 가련합니다. 실로 성경은 사람의 “생명”과 “호흡”을 같은 것으로 다룹니다(구약의 nephesh, 신약의 psuchē).","zh":"圣经指出，肉体的生命在于它的气息——这使我们在肉体里的生命脆弱，甚至可怜。的确，圣经将人的“生命”与“气息”视为同一回事（旧约中的nephesh，新约中的psuchē）。","es":"La Biblia señala el hecho de que la vida de la carne está en su aliento — y eso hace que nuestra vida en la carne sea frágil, incluso lamentable. En efecto, la Biblia trata la “vida” del hombre y el “aliento” como lo mismo (nephesh en el Antiguo Testamento, psuchē en el Nuevo Testamento)."}},
 {"t":"s","v":["job7_7","ps146_3"]},
 {"t":"p","x":{"en":"Our flesh lives by its breath. Once the breath is cut off, the flesh dies. So the “life” we have in the flesh is only a breath — something with a beginning and an end (Hebrews 9:27). It is not to this body, which has a beginning and an end, that God wants to give His life; such a body cannot inherit the kingdom of heaven (1 Corinthians 15:50). Rather, it is to the spirit that God wants to give His life.","ko":"우리의 육신은 그 호흡으로 삽니다. 호흡이 끊어지면 육신은 죽습니다. 그러므로 우리가 육신 안에 가진 “생명”은 한낱 호흡일 뿐이며 — 시작과 끝이 있는 것입니다(히브리서 9:27). 하나님께서 자신의 생명을 주고자 하시는 대상은 시작과 끝이 있는 이 몸이 아닙니다. 그런 몸은 천국을 유업으로 받을 수 없습니다(고린도전서 15:50). 오히려 하나님께서 자신의 생명을 주고자 하시는 대상은 영입니다.","zh":"我们的肉体靠气息而活。一旦气息断绝，肉体就死了。所以我们在肉体里所拥有的“生命”不过是一口气息——是有始有终的（希伯来书9:27）。神所要赐下祂生命的，并不是这有始有终的身体；这样的身体不能承受天国（哥林多前书15:50）。相反，神所要赐下祂生命的乃是灵。","es":"Nuestra carne vive por su aliento. Una vez que el aliento se corta, la carne muere. Así que la “vida” que tenemos en la carne es solo un aliento — algo con un principio y un fin (Hebreos 9:27). No es a este cuerpo, que tiene un principio y un fin, al que Dios quiere dar Su vida; tal cuerpo no puede heredar el reino de los cielos (1 Corintios 15:50). Más bien, es al espíritu al que Dios quiere dar Su vida."}},

 {"t":"h","x":{"en":"The Life (Zoē) of Jesus","ko":"예수님의 생명(조에)","zh":"耶稣的生命（Zoē）","es":"La vida (Zoē) de Jesús"}},
 {"t":"p","x":{"en":"The life we ought to live for — the life we can never give up — is the life that is in God, in Jesus: zoē.","ko":"우리가 위하여 살아야 할 생명 — 결코 포기할 수 없는 생명 — 은 하나님 안에, 예수님 안에 있는 생명, 곧 조에입니다.","zh":"我们理当为之而活的生命——我们绝不能放弃的生命——就是在神里面、在耶稣里面的生命：zoē。","es":"La vida por la cual debemos vivir — la vida que nunca podemos abandonar — es la vida que está en Dios, en Jesús: zoē."}},
 {"t":"s","v":["jn1_4"]},
 {"t":"p","x":{"en":"In the Word that was in the beginning there was life (zoē). And that life came in the flesh (John 1:14). Thus the flesh, the very body of Jesus, is the Word — the life that never ends. Jesus is the resurrection and the life (John 11:25). Though He died, He rose again in three days and showed the true image of life (Acts 3:15).","ko":"태초에 계셨던 말씀 안에 생명(조에)이 있었습니다. 그리고 그 생명이 육신으로 오셨습니다(요한복음 1:14). 이처럼 육신, 곧 예수님의 바로 그 몸이 말씀이며 — 결코 끝나지 않는 생명입니다. 예수님은 부활이요 생명이십니다(요한복음 11:25). 그분은 죽으셨으나 사흘 만에 다시 살아나셔서 생명의 참된 형상을 보여 주셨습니다(사도행전 3:15).","zh":"在太初就有的道里面有生命（zoē）。这生命成了肉身（约翰福音1:14）。因此，那肉体，就是耶稣的身体，正是道——永不止息的生命。耶稣是复活，也是生命（约翰福音11:25）。祂虽然死了，却在三天后复活，显明了生命真正的形象（使徒行传3:15）。","es":"En la Palabra que era en el principio había vida (zoē). Y esa vida vino en la carne (Juan 1:14). Así, la carne, el cuerpo mismo de Jesús, es la Palabra — la vida que nunca termina. Jesús es la resurrección y la vida (Juan 11:25). Aunque murió, resucitó en tres días y mostró la verdadera imagen de la vida (Hechos 3:15)."}},
 {"t":"s","v":["jn6_63"]},
 {"t":"p","x":{"en":"Because God is life, He wants to give His life to us — not to the flesh but to the spirit. What God wants to save is the spirit, not the flesh. We must choose this life for our spirit (Deuteronomy 30:19). But how do we receive this life?","ko":"하나님은 생명이시기에, 자신의 생명을 우리에게 주고자 하십니다 — 육신이 아니라 영에게 말입니다. 하나님께서 구원하고자 하시는 것은 영이지 육신이 아닙니다. 우리는 우리의 영을 위하여 이 생명을 택해야 합니다(신명기 30:19). 그러면 우리는 이 생명을 어떻게 받습니까?","zh":"因为神是生命，祂愿意将祂的生命赐给我们——不是赐给肉体，而是赐给灵。神所要拯救的是灵，不是肉体。我们必须为我们的灵拣选这生命（申命记30:19）。但我们如何领受这生命呢？","es":"Porque Dios es vida, Él quiere dar Su vida a nosotros — no a la carne sino al espíritu. Lo que Dios quiere salvar es el espíritu, no la carne. Debemos escoger esta vida para nuestro espíritu (Deuteronomio 30:19). Pero ¿cómo recibimos esta vida?"}},

 {"t":"h","x":{"en":"The Way We Receive Life","ko":"우리가 생명을 받는 길","zh":"我们领受生命的方式","es":"La manera en que recibimos la vida"}},
 {"t":"p","x":{"en":"It is the word of God that gives life to the spirit.","ko":"영에게 생명을 주는 것은 하나님의 말씀입니다.","zh":"赐生命给灵的，正是神的道。","es":"Es la palabra de Dios la que da vida al espíritu."}},
 {"t":"s","v":["jn15_7"]},
 {"t":"p","x":{"en":"Remaining in God, in Jesus, means remaining in His word. It means remaining in His life, maintaining a relationship with Him. And the way He gives us His life is through His command.","ko":"하나님 안에, 예수님 안에 거한다는 것은 그분의 말씀 안에 거하는 것을 뜻합니다. 그것은 그분의 생명 안에 거하며 그분과의 관계를 유지하는 것을 뜻합니다. 그리고 그분이 우리에게 자신의 생명을 주시는 방식은 그분의 명령을 통해서입니다.","zh":"住在神里面、住在耶稣里面，就是住在祂的道里面。这就是住在祂的生命里，与祂保持关系。而祂将祂的生命赐给我们的方式，乃是藉着祂的命令。","es":"Permanecer en Dios, en Jesús, significa permanecer en Su palabra. Significa permanecer en Su vida, manteniendo una relación con Él. Y la manera en que Él nos da Su vida es por medio de Su mandamiento."}},
 {"t":"summary","mark":"✳","title":{"en":"His life","ko":"그분의 생명","zh":"祂的生命","es":"Su vida"},"rows":[
   {"v":{"en":"Does not spoil or fade","ko":"썩지 않고 쇠하지 않음","zh":"不朽坏，不衰残","es":"No se corrompe ni se marchita"},"s":{"en":"1 Peter 1:4","ko":"베드로전서 1:4","zh":"彼得前书1:4","es":"1 Pedro 1:4"}},
   {"v":{"en":"Everlasting, no end","ko":"영원하며 끝이 없음","zh":"永远长存，没有穷尽","es":"Eterna, sin fin"},"s":{"en":"it never runs out","ko":"결코 소진되지 않음","zh":"永不枯竭","es":"nunca se agota"}},
   {"v":{"en":"Flawless","ko":"흠이 없음","zh":"毫无瑕疵","es":"Sin defecto"},"s":{"en":"without blemish — Ephesians 5:27; Hebrews 7:3","ko":"티가 없음 — 에베소서 5:27; 히브리서 7:3","zh":"毫无瑕疵——以弗所书5:27；希伯来书7:3","es":"sin mancha — Efesios 5:27; Hebreos 7:3"}}
 ]},
 {"t":"s","v":["jn12_50"]},
 {"t":"p","x":{"en":"So if we choose life for the spirit then, whether we like it or not, we have to receive His word as command. And when we obey His command, the word becomes life in our spirit. God wants to pour out His life to us all, yet He does not override our free will; He wants us to use our free will to choose to obey, and so to receive life. His word is spirit and life: when it enters the spirit, it becomes life to the spirit “me.”","ko":"그러므로 우리가 영을 위하여 생명을 택한다면, 좋든 싫든 우리는 그분의 말씀을 명령으로 받아들여야 합니다. 그리고 우리가 그분의 명령에 순종할 때, 그 말씀은 우리 영 안에서 생명이 됩니다. 하나님은 우리 모두에게 자신의 생명을 부어 주기 원하시지만, 우리의 자유의지를 무시하지 않으십니다. 그분은 우리가 자유의지를 사용하여 순종하기를 택함으로써 생명을 받기를 원하십니다. 그분의 말씀은 영이요 생명입니다. 그것이 영 안으로 들어올 때, 그것은 영 “나”에게 생명이 됩니다.","zh":"所以，如果我们为灵拣选生命，那么无论我们喜欢与否，都必须把祂的道当作命令来领受。当我们顺从祂的命令时，这道就在我们的灵里成为生命。神愿意将祂的生命浇灌给我们众人，然而祂不越过我们的自由意志；祂愿意我们运用自由意志拣选顺从，从而领受生命。祂的道就是灵，就是生命：当它进入灵里时，就成为灵“我”的生命。","es":"Así que, si escogemos la vida para el espíritu, entonces, nos guste o no, tenemos que recibir Su palabra como mandamiento. Y cuando obedecemos Su mandamiento, la palabra se hace vida en nuestro espíritu. Dios quiere derramar Su vida sobre todos nosotros, pero no pasa por encima de nuestro libre albedrío; Él quiere que usemos nuestro libre albedrío para escoger obedecer, y así recibir vida. Su palabra es espíritu y vida: cuando entra en el espíritu, se hace vida para el espíritu “yo”."}},
 {"t":"flow","title":{"en":"How life comes","ko":"생명이 오는 방식","zh":"生命如何临到","es":"Cómo llega la vida"},"steps":[
   {"b":{"en":"God","ko":"하나님","zh":"神","es":"Dios"},"s":{"en":"the source of life","ko":"생명의 근원","zh":"生命的源头","es":"la fuente de la vida"}},
   {"b":{"en":"the Word","ko":"말씀","zh":"道","es":"la Palabra"},"s":{"en":"God speaks to us","ko":"하나님이 우리에게 말씀하심","zh":"神向我们说话","es":"Dios nos habla"}},
   {"b":{"en":"as command","ko":"명령으로","zh":"作为命令","es":"como mandamiento"},"s":{"en":"the Word is given as command","ko":"말씀이 명령으로 주어짐","zh":"道作为命令被赐下","es":"la Palabra se da como mandamiento"},"key":true},
   {"b":{"en":"the Spirit","ko":"영","zh":"灵","es":"el espíritu"},"s":{"en":"receives it, and lives","ko":"그것을 받아 살아남","zh":"领受它，就活了","es":"lo recibe, y vive"}}
 ]},
 {"t":"q","items":[{"en":"What is your relationship with the word of God? How do you respond to His word in your daily life? Discuss.","ko":"당신은 하나님의 말씀과 어떤 관계에 있습니까? 당신은 일상의 삶에서 그분의 말씀에 어떻게 반응합니까? 나누어 봅시다.","zh":"你与神的道有着怎样的关系？在日常生活中，你如何回应祂的道？请讨论。","es":"¿Cuál es tu relación con la palabra de Dios? ¿Cómo respondes a Su palabra en tu vida diaria? Comenta."}]},
 {"t":"lesson","n":"2.3","title":{"en":"Life After Death","ko":"죽음 이후의 삶","zh":"死后的生命","es":"La vida después de la muerte"}},
 {"t":"p","x":{"en":"What happens to us after we die? The Bible says that, because our body is made of the dust of the ground, after death it returns to dust (Genesis 3:19); and because our spirit came from God, it needs to return to God.","ko":"우리가 죽은 후에는 어떻게 될까요? 성경은 이렇게 말합니다. 우리의 몸은 땅의 흙으로 지어졌기에 죽은 후에는 흙으로 돌아가고(창세기 3:19), 우리의 영은 하나님께로부터 왔기에 하나님께로 돌아가야 합니다.","zh":"我们死后会怎样呢？圣经说，因为我们的身体是用地上的尘土造的，死后就归于尘土（创世记3:19）；又因为我们的灵来自神，就必须归回到神那里。","es":"¿Qué nos sucede después de morir? La Biblia dice que, como nuestro cuerpo fue hecho del polvo de la tierra, después de la muerte vuelve al polvo (Génesis 3:19); y como nuestro espíritu vino de Dios, necesita volver a Dios."}},

 {"t":"h","x":{"en":"Life After Death","ko":"죽음 이후의 삶","zh":"死后的生命","es":"La vida después de la muerte"}},
 {"t":"p","x":{"en":"Since Adam sinned, however, all people sinned in him and death came to all (Romans 5:12; 1 Corinthians 15:21). Thereafter no one could return to God, because of sin and the price of sin, death. What is more, the spirits that cannot return to God — those who do not believe in Him and His word — remain in a place called Hades (Luke 16:22–23).","ko":"그러나 아담이 죄를 지은 이후로, 모든 사람이 그 안에서 죄를 지었고 죽음이 모든 사람에게 이르렀습니다(로마서 5:12; 고린도전서 15:21). 그때부터 아무도 하나님께 돌아갈 수 없게 되었으니, 죄와 죄의 값인 죽음 때문입니다. 더욱이 하나님께 돌아갈 수 없는 영들, 곧 그분과 그분의 말씀을 믿지 않는 자들은 음부라 불리는 곳에 머뭅니다(누가복음 16:22–23).","zh":"然而，自从亚当犯了罪，众人就都在他里面犯了罪，死也临到了众人（罗马书5:12；哥林多前书15:21）。从此，没有人能够归回到神那里，这是因为罪，以及罪的代价——死亡。不仅如此，那些不能归回到神那里的灵——就是不信他和他话语的人——仍留在一个叫作阴间的地方（路加福音16:22–23）。","es":"Sin embargo, desde que Adán pecó, todos pecaron en él y la muerte alcanzó a todos (Romanos 5:12; 1 Corintios 15:21). Desde entonces nadie pudo volver a Dios, a causa del pecado y del precio del pecado: la muerte. Es más, los espíritus que no pueden volver a Dios —los que no creen en Él ni en su palabra— permanecen en un lugar llamado el Hades (Lucas 16:22–23)."}},
 {"t":"s","v":["lk16_22"]},
 {"t":"h","x":{"en":"Where Is Hades?","ko":"음부는 어디인가?","zh":"阴间在哪里？","es":"¿Dónde está el Hades?"}},
 {"t":"p","x":{"en":"Hades (ho hadēs) is a Greek word for “the underworld,” but also for “the world” or “the earth” (see Matthew 16:18). So “Hades” in the Bible refers to none other than the world we live in. Included within Hades is another spiritual space called the “Abyss” (Luke 8:31; Revelation 20:3), where the spirits that cannot return to God are thrown at some point after death, before being cast into the fire of hell in the end.","ko":"음부(ho hadēs)는 “지하 세계”를 뜻하는 헬라어이지만, “세상” 또는 “땅”을 뜻하기도 합니다(마태복음 16:18 참조). 그러므로 성경에서 “음부”는 다름 아닌 우리가 사는 이 세상을 가리킵니다. 음부 안에는 “무저갱”이라 불리는 또 다른 영적 공간이 있는데(누가복음 8:31; 요한계시록 20:3), 하나님께 돌아갈 수 없는 영들이 죽은 후 어느 시점에 그곳에 던져지며, 마침내 지옥 불에 던져지기 전까지 그곳에 머뭅니다.","zh":"阴间（ho hadēs）是希腊文，意思是“阴府”，但也指“世界”或“地”（参马太福音16:18）。所以圣经中的“阴间”所指的，正是我们所居住的这个世界。在阴间之内还有另一个属灵的空间，称为“无底坑”（路加福音8:31；启示录20:3）；那些不能归回到神那里的灵，死后会在某个时候被扔进那里，最终再被扔进地狱的火里。","es":"El Hades (ho hadēs) es una palabra griega que significa “el inframundo”, pero también “el mundo” o “la tierra” (véase Mateo 16:18). Por eso, el “Hades” en la Biblia no se refiere a otra cosa que al mundo en que vivimos. Dentro del Hades hay otro espacio espiritual llamado el “Abismo” (Lucas 8:31; Apocalipsis 20:3), donde los espíritus que no pueden volver a Dios son arrojados en algún momento después de la muerte, antes de ser lanzados finalmente al fuego del infierno."}},
 {"t":"h","x":{"en":"Where Do Believers Go?","ko":"믿는 자들은 어디로 가는가?","zh":"信徒去哪里？","es":"¿A dónde van los creyentes?"}},
 {"t":"p","x":{"en":"In the Old Testament, after believers died their spirits went to a place called “Abraham’s side” (Luke 16:22) — a spiritual space that is a portion of the third heaven. The same location is later called “paradise” in the New Testament (Luke 23:43). So today the spirits of believers return to God — to paradise.","ko":"구약에서는 믿는 자들이 죽은 후 그들의 영이 “아브라함의 품”이라 불리는 곳으로 갔는데(누가복음 16:22), 이는 셋째 하늘의 일부인 영적 공간입니다. 같은 곳이 신약에서는 후에 “낙원”이라 불립니다(누가복음 23:43). 그러므로 오늘날 믿는 자들의 영은 하나님께로 — 곧 낙원으로 — 돌아갑니다.","zh":"在旧约里，信徒死后他们的灵会去到一个叫作“亚伯拉罕的怀里”的地方（路加福音16:22）——那是属灵的空间，是第三层天的一部分。到了新约，同一个地方后来被称为“乐园”（路加福音23:43）。所以今天，信徒的灵归回到神那里——归到乐园。","es":"En el Antiguo Testamento, después de que los creyentes morían, sus espíritus iban a un lugar llamado “el seno de Abraham” (Lucas 16:22) —un espacio espiritual que es una parte del tercer cielo. Ese mismo lugar se llama más tarde “el paraíso” en el Nuevo Testamento (Lucas 23:43). Así que hoy los espíritus de los creyentes vuelven a Dios, al paraíso."}},
 {"t":"hades","title":{"en":"Where the spirits go","ko":"영들이 가는 곳","zh":"灵魂的去处","es":"A dónde van los espíritus"},"q1":{"en":"Where is Hades?","ko":"음부는 어디인가?","zh":"阴间在哪里？","es":"¿Dónde está el Hades?"},"a1":{"en":"Hades = Hell","ko":"음부 = 지옥","zh":"阴间 = 地狱","es":"El Hades = el infierno"},"q2":{"en":"Where do believers go?","ko":"믿는 자들은 어디로 가는가?","zh":"信徒去哪里？","es":"¿A dónde van los creyentes?"},"a2":{"en":"Paradise — the 3rd heaven","ko":"낙원 — 셋째 하늘","zh":"乐园——第三层天","es":"El paraíso — el tercer cielo"}},
 {"t":"h","x":{"en":"Who Are “Unclean Spirits”?","ko":"“더러운 영”은 누구인가?","zh":"谁是“污鬼”？","es":"¿Quiénes son los “espíritus inmundos”?"}},
 {"t":"p","x":{"en":"When the spirit of a person leaves the body without having made a relationship with Jesus while alive, it is unclean — because of sin. Unclean spirits remain in Hades, that is, the world, and are called “unclean spirits” (Mark 1:23). To have a relationship with Jesus, our spirits have to be washed and cleansed with the blood of Jesus while we are still alive in the flesh. Then our spirits become “clean” and can return to God after the flesh dies.","ko":"사람이 살아 있는 동안 예수님과 관계를 맺지 못한 채 그 영이 몸을 떠나면, 그 영은 죄로 인해 더럽습니다. 더러운 영들은 음부, 곧 세상에 머물며 “더러운 영”이라 불립니다(마가복음 1:23). 예수님과 관계를 맺으려면, 우리가 아직 육신으로 살아 있는 동안 우리의 영이 예수님의 피로 씻김과 정결함을 받아야 합니다. 그러면 우리의 영은 “깨끗”해져서, 육신이 죽은 후에 하나님께 돌아갈 수 있습니다.","zh":"当一个人的灵在活着的时候未曾与耶稣建立关系，就离开了身体，这灵便是污秽的——因为罪的缘故。污秽的灵留在阴间，也就是这世界，被称为“污鬼”（马可福音1:23）。要与耶稣建立关系，我们的灵必须趁我们还活在肉体里的时候，被耶稣的宝血洗净、洁净。这样，我们的灵就成为“洁净”的，在肉体死后就能归回到神那里。","es":"Cuando el espíritu de una persona deja el cuerpo sin haber establecido una relación con Jesús mientras vivía, está inmundo, a causa del pecado. Los espíritus inmundos permanecen en el Hades, es decir, en el mundo, y son llamados “espíritus inmundos” (Marcos 1:23). Para tener una relación con Jesús, nuestro espíritu tiene que ser lavado y limpiado con la sangre de Jesús mientras todavía estamos vivos en la carne. Entonces nuestro espíritu llega a ser “limpio” y puede volver a Dios después de que la carne muere."}},
 {"t":"summary","mark":"✳","title":{"en":"Unclean spirits","ko":"더러운 영","zh":"污鬼","es":"Los espíritus inmundos"},"rows":[
   {"v":{"en":"No part with Jesus","ko":"예수님과 상관이 없음","zh":"与耶稣无份","es":"Sin parte con Jesús"},"s":{"en":"Mark 1:24; John 13:8","ko":"마가복음 1:24; 요한복음 13:8","zh":"马可福音1:24；约翰福音13:8","es":"Marcos 1:24; Juan 13:8"}},
   {"v":{"en":"Never washed","ko":"결코 씻기지 않음","zh":"从未被洗净","es":"Nunca lavados"},"s":{"en":"spirits of unbelievers, unwashed by the blood of Jesus","ko":"예수님의 피로 씻기지 않은 불신자들의 영","zh":"未曾被耶稣宝血洗净的不信者的灵","es":"espíritus de los incrédulos, no lavados por la sangre de Jesús"}},
   {"v":{"en":"Seeking rest","ko":"안식을 찾음","zh":"寻找安歇","es":"Buscando reposo"},"s":{"en":"they pass through “arid places seeking rest,” but find none","ko":"그들은 “안식을 찾아 물 없는 곳”을 다니지만, 찾지 못합니다","zh":"他们走遍“无水之地，寻求安歇”，却寻不着","es":"pasan por “lugares áridos buscando reposo”, pero no lo hallan"}}
 ]},
 {"t":"q","items":[{"en":"How does this teaching about life after death affect the way you see your own life? What do you think will happen to you after you die? What about your family and friends?","ko":"죽음 이후의 삶에 관한 이 가르침은 당신 자신의 삶을 바라보는 방식에 어떤 영향을 줍니까? 당신은 죽은 후에 자신에게 무슨 일이 일어날 것이라고 생각합니까? 당신의 가족과 친구들은 어떻습니까?","zh":"关于死后生命的这个教导，如何影响你看待自己人生的方式？你认为自己死后会怎样？你的家人和朋友又会如何呢？","es":"¿Cómo afecta esta enseñanza sobre la vida después de la muerte la manera en que ves tu propia vida? ¿Qué crees que te sucederá después de morir? ¿Y a tu familia y a tus amigos?"}]},
 {"t":"lesson","n":"2.4","title":{"en":"Resurrection","ko":"부활","zh":"复活","es":"La resurrección"}},
 {"t":"p","x":{"en":"The Bible says that we live once in our flesh, and when the flesh dies our spirits live on — either in heaven or in hell. This is significant, because all people will be raised to live in their spiritual bodies.","ko":"성경은 우리가 육신으로 한 번 살며, 육신이 죽으면 우리의 영은 계속 살아간다고 말합니다 — 천국에서든 지옥에서든 말입니다. 이것은 중요합니다. 왜냐하면 모든 사람이 부활하여 자신의 영적인 몸으로 살게 될 것이기 때문입니다.","zh":"圣经说，我们在肉体中活一次，当肉体死去时，我们的灵仍继续存活——或在天堂，或在地狱。这一点意义重大，因为所有人都将复活，以属灵的身体存活。","es":"La Biblia dice que vivimos una sola vez en nuestra carne, y cuando la carne muere nuestro espíritu sigue viviendo — sea en el cielo o en el infierno. Esto es significativo, porque todas las personas serán resucitadas para vivir en su cuerpo espiritual."}},

 {"t":"h","x":{"en":"Jesus Christ, the Firstfruits of Resurrection","ko":"부활의 첫 열매이신 예수 그리스도","zh":"耶稣基督，复活的初熟果子","es":"Jesucristo, las primicias de la resurrección"}},
 {"t":"s","v":["1co15_20"]},
 {"t":"p","x":{"en":"Jesus Christ is the firstfruits of resurrection. Through His resurrection He showed what it is like to have the spiritual body: He let the disciples touch His side and hands — the spiritual body that has flesh and bones (Luke 24:39). Jesus rose in the same body He had died in, for His flesh is the incarnate Word, Spirit (John 1:1, 14; 6:63). That is why, even after His death and resurrection, He still carried the same scars, which will remain forever (Revelation 5:6).","ko":"예수 그리스도는 부활의 첫 열매이십니다. 그분은 자신의 부활을 통해 영적인 몸을 가진다는 것이 어떤 것인지 보여 주셨습니다. 그분은 제자들이 자신의 옆구리와 손을 만지게 하셨는데, 이는 살과 뼈를 가진 영적인 몸이었습니다(누가복음 24:39). 예수님은 자신이 죽으셨던 바로 그 몸으로 부활하셨는데, 이는 그분의 육신이 성육신하신 말씀, 곧 영이시기 때문입니다(요한복음 1:1, 14; 6:63). 그렇기 때문에 그분은 죽으시고 부활하신 후에도 여전히 동일한 상처를 지니고 계셨으며, 그 상처는 영원히 남아 있을 것입니다(요한계시록 5:6).","zh":"耶稣基督是复活的初熟果子。祂借着自己的复活，向人显明拥有属灵身体是何等光景：祂让门徒摸祂的肋旁和手——那是有骨有肉的属灵身体（路加福音24:39）。耶稣是以祂死时的同一个身体复活的，因为祂的肉体就是成为肉身的道，就是灵（约翰福音1:1、14；6:63）。正因如此，祂在死而复活之后，仍带着同样的伤痕，这伤痕将永远长存（启示录5:6）。","es":"Jesucristo es las primicias de la resurrección. Por medio de su resurrección mostró cómo es tener el cuerpo espiritual: dejó que los discípulos tocaran su costado y sus manos — el cuerpo espiritual que tiene carne y huesos (Lucas 24:39). Jesús resucitó en el mismo cuerpo en que había muerto, porque su carne es la Palabra hecha carne, Espíritu (Juan 1:1, 14; 6:63). Por eso, aun después de su muerte y resurrección, seguía llevando las mismas cicatrices, que permanecerán para siempre (Apocalipsis 5:6)."}},

 {"t":"h","x":{"en":"Everyone Will Be Raised","ko":"모든 사람이 부활할 것입니다","zh":"所有人都将复活","es":"Todos serán resucitados"}},
 {"t":"s","v":["jn5_29","ac24_15","2ti4_1"]},
 {"t":"p","x":{"en":"All people will be raised in the end. Our resurrection, however, is not like that of Christ. Christ died and rose in the same body, because His body is spirit. But our resurrection is not of our flesh — our flesh will perish when it dies and cannot live forever. Rather, our spirit will be raised to become the body. Resurrection is not only for those going to heaven; it is for all.","ko":"모든 사람은 마지막에 부활할 것입니다. 그러나 우리의 부활은 그리스도의 부활과 같지 않습니다. 그리스도는 죽으시고 동일한 몸으로 부활하셨는데, 이는 그분의 몸이 영이기 때문입니다. 그러나 우리의 부활은 우리 육신의 부활이 아닙니다 — 우리의 육신은 죽으면 썩어 없어지며 영원히 살 수 없습니다. 오히려 우리의 영이 부활하여 몸이 될 것입니다. 부활은 천국에 가는 사람들만을 위한 것이 아니라 모든 사람을 위한 것입니다.","zh":"所有人最终都将复活。然而，我们的复活与基督的复活不同。基督死了，又以同一个身体复活，因为祂的身体就是灵。但我们的复活并不是肉体的复活——我们的肉体死后必朽坏，不能永远存活。反倒是我们的灵要复活，成为身体。复活不仅是为那些要进天堂的人，也是为所有人。","es":"Todas las personas serán resucitadas al final. Sin embargo, nuestra resurrección no es como la de Cristo. Cristo murió y resucitó en el mismo cuerpo, porque su cuerpo es espíritu. Pero nuestra resurrección no es la de nuestra carne — nuestra carne perecerá cuando muera y no puede vivir para siempre. Más bien, nuestro espíritu será resucitado para llegar a ser el cuerpo. La resurrección no es solo para los que van al cielo; es para todos."}},
 {"t":"p","x":{"en":"The resurrection of the wicked — “the resurrection to condemnation” — is to be thrown into “the second death,” which is hell, “the lake of fire” (Revelation 20:14–15). There the raised spirits will feel the horrors and pains of death forever.","ko":"악인의 부활은 — “정죄의 부활” — “둘째 사망”, 곧 지옥인 “불못”에 던져지는 것입니다(요한계시록 20:14–15). 그곳에서 부활한 영들은 영원히 사망의 두려움과 고통을 느끼게 될 것입니다.","zh":"恶人的复活——“定罪的复活”——就是被扔进“第二次的死”，也就是地狱，“火湖”（启示录20:14–15）。在那里，复活的灵将永远感受死亡的恐怖与痛苦。","es":"La resurrección de los malvados — “la resurrección de condenación” — es ser arrojados a “la segunda muerte”, que es el infierno, “el lago de fuego” (Apocalipsis 20:14–15). Allí los espíritus resucitados sentirán los horrores y los dolores de la muerte para siempre."}},
 {"t":"s","v":["mk9_43"]},
 {"t":"p","x":{"en":"The resurrection like that of Christ, on the other hand, is “the resurrection to life” (John 5:29), the resurrection into the glorious body (Philippians 3:21). Through this resurrection we can have eternal life — to live joyfully, happily, gloriously and eternally. So far it is only Christ who has been raised from the dead; but when He returns, there will be the next order of resurrection, called “the first resurrection.”","ko":"반면에 그리스도와 같은 부활은 “생명의 부활”(요한복음 5:29)이요, 영광스러운 몸으로의 부활입니다(빌립보서 3:21). 이 부활을 통해 우리는 영생을 누릴 수 있습니다 — 기쁘고 행복하며 영광스럽고 영원하게 사는 것입니다. 지금까지는 오직 그리스도만이 죽은 자 가운데서 부활하셨습니다. 그러나 그분이 다시 오실 때에는 “첫째 부활”이라 불리는 그다음 차례의 부활이 있을 것입니다.","zh":"另一方面，像基督那样的复活，乃是“生命的复活”（约翰福音5:29），是进入荣耀身体的复活（腓立比书3:21）。借着这复活，我们可以得着永生——喜乐、幸福、荣耀且永远地活着。到目前为止，唯有基督从死里复活了；但当祂再来时，将有下一批次序的复活，称为“头一次的复活”。","es":"En cambio, la resurrección como la de Cristo es “la resurrección de vida” (Juan 5:29), la resurrección al cuerpo glorioso (Filipenses 3:21). Por medio de esta resurrección podemos tener vida eterna — vivir con gozo, felicidad, gloria y eternamente. Hasta ahora solo Cristo ha resucitado de entre los muertos; pero cuando Él regrese, habrá el siguiente orden de resurrección, llamado “la primera resurrección”."}},
 {"t":"s","v":["1co15_23"]},
 {"t":"s","v":["rev20_4"]},
 {"t":"p","x":{"en":"The first resurrection is the resurrection into the glorious body. It is for “those who belong to Him” and for “those who had been beheaded because of their testimony about Jesus and because of the word of God.” Those who share in the first resurrection are blessed, because the second death has no power over them. This means that those who do not share in the first resurrection, and must come instead to the second resurrection, may not escape the second death.","ko":"첫째 부활은 영광스러운 몸으로의 부활입니다. 그것은 “그리스도께 속한 자들”과 “예수를 증언함과 하나님의 말씀으로 인하여 목 베임을 당한 자들”을 위한 것입니다. 첫째 부활에 참여하는 자들은 복이 있으니, 이는 둘째 사망이 그들을 다스리는 권세가 없기 때문입니다. 이것은 첫째 부활에 참여하지 못하고 대신 둘째 부활로 나아가야 하는 자들은 둘째 사망을 피하지 못할 수 있음을 뜻합니다.","zh":"头一次的复活是进入荣耀身体的复活。它是为“属基督的人”，也是为“那些因给耶稣作见证、并因神的道而被斩首的人”。有分于头一次复活的人有福了，因为第二次的死在他们身上没有权柄。这意味着那些没有分于头一次复活、反倒必须来到第二次复活的人，恐怕难以逃脱第二次的死。","es":"La primera resurrección es la resurrección al cuerpo glorioso. Es para “los que le pertenecen” y para “los que habían sido decapitados por su testimonio acerca de Jesús y por la palabra de Dios”. Los que participan en la primera resurrección son bienaventurados, porque la segunda muerte no tiene poder sobre ellos. Esto significa que los que no participan en la primera resurrección, y en cambio deben venir a la segunda resurrección, quizá no escapen de la segunda muerte."}},
 {"t":"callout","x":{"en":"Being born a human was beyond our choice — but resurrection will be the result of our choice. Therefore we must choose whether we want to be raised to life or to condemnation.","ko":"사람으로 태어난 것은 우리의 선택을 넘어선 일이었습니다 — 그러나 부활은 우리의 선택의 결과가 될 것입니다. 그러므로 우리는 생명으로 부활하기를 원하는지 정죄로 부활하기를 원하는지 선택해야 합니다.","zh":"生为人是我们无法选择的——但复活将是我们选择的结果。因此，我们必须选择：要复活得生命，还是复活受定罪。","es":"Nacer como ser humano estuvo fuera de nuestra elección — pero la resurrección será el resultado de nuestra elección. Por lo tanto, debemos elegir si queremos ser resucitados para vida o para condenación."}},
 {"t":"p","x":{"en":"If our spirits have been cleansed by the blood of Jesus while we are alive in the flesh, then we have to press on to take hold of this prize — the first resurrection — that the Lord has set before us (Philippians 3:14). After receiving His blood, His life, into our spirit, that life must continue to grow; and for that we have to eat the word and be cleansed (sanctified) by water (1 Corinthians 1:2; Ephesians 5:26). Let us open our eyes and see the glorious eternity promised for us.","ko":"우리가 육신으로 살아 있는 동안에 우리의 영이 예수의 피로 깨끗해졌다면, 우리는 주님께서 우리 앞에 두신 이 상 — 첫째 부활 — 을 붙잡기 위해 힘써 나아가야 합니다(빌립보서 3:14). 그분의 피, 곧 그분의 생명을 우리의 영 안에 받아들인 후에는 그 생명이 계속 자라가야 하며, 그러기 위해 우리는 말씀을 먹고 물로 깨끗함(성결)을 입어야 합니다(고린도전서 1:2; 에베소서 5:26). 우리를 위해 약속된 영광스러운 영원을 보도록 우리의 눈을 엽시다.","zh":"我们若在肉体活着的时候，灵已被耶稣的血洗净，就必须竭力向前，抓住主摆在我们面前的这奖赏——头一次的复活（腓立比书3:14）。在把祂的血、祂的生命接进我们的灵之后，那生命必须继续长大；为此我们必须吃这道，并借着水得洁净（成圣）（哥林多前书1:2；以弗所书5:26）。让我们睁开眼睛，看见那为我们所应许的荣耀永恒。","es":"Si nuestro espíritu ha sido limpiado por la sangre de Jesús mientras estamos vivos en la carne, entonces debemos proseguir para asir este premio — la primera resurrección — que el Señor ha puesto delante de nosotros (Filipenses 3:14). Después de recibir su sangre, su vida, en nuestro espíritu, esa vida debe seguir creciendo; y para ello tenemos que comer la palabra y ser limpiados (santificados) por el agua (1 Corintios 1:2; Efesios 5:26). Abramos los ojos y veamos la gloriosa eternidad prometida para nosotros."}},
 {"t":"q","items":[{"en":"How does this new understanding — of life, of life after death, and of yourself — change your thinking about your life and your future? How would your life look different if it were aiming for the first resurrection? Discuss.","ko":"생명에 대한, 죽음 이후의 삶에 대한, 그리고 자기 자신에 대한 이 새로운 이해는 당신의 삶과 미래에 대한 생각을 어떻게 바꾸어 놓습니까? 만일 당신의 삶이 첫째 부활을 목표로 삼는다면, 당신의 삶은 어떻게 달라 보이겠습니까? 함께 나누어 봅시다.","zh":"这对生命、对死后的生命、以及对你自己的全新认识——如何改变你对自己人生和未来的看法？如果你的人生以头一次的复活为目标，你的人生会有什么不同？请讨论。","es":"¿Cómo cambia esta nueva comprensión — de la vida, de la vida después de la muerte y de ti mismo — tu manera de pensar acerca de tu vida y tu futuro? ¿Cómo se vería diferente tu vida si estuviera orientada hacia la primera resurrección? Comenta."}]}

]
};

