/* Chapter 1 — The Spiritual World (Stage 1, Lessons 1.1–1.4) */
window.CHAPTER = {
"id":"step-1",
"verses":{
 "2co4_18":{"ref":{"en":"2 Corinthians 4:18","ko":"고린도후서 4:18","zh":"哥林多后书 4:18","es":"2 Corintios 4:18"},"t":{"en":"…while we don’t look at the things which are seen, but at the things which are not seen. For the things which are seen are temporal, but the things which are not seen are eternal.","ko":"우리가 주목하는 것은 보이는 것이 아니요 보이지 않는 것이니, 보이는 것은 잠깐이요 보이지 않는 것은 영원함이라.","zh":"原来我们不是顾念所见的，乃是顾念所不见的；因为所见的是暂时的，所不见的是永远的。","es":"…no mirando nosotros las cosas que se ven, sino las que no se ven; pues las cosas que se ven son temporales, pero las que no se ven son eternas."}},
 "col1_16":{"ref":{"en":"Colossians 1:16","ko":"골로새서 1:16","zh":"歌罗西书 1:16","es":"Colosenses 1:16"},"t":{"en":"For by him all things were created, in the heavens and on the earth, things visible and things invisible, whether thrones or dominions or principalities or powers. All things have been created through him and for him.","ko":"만물이 그에게서 창조되되 하늘과 땅에서 보이는 것들과 보이지 않는 것들과 혹은 왕권들이나 주권들이나 통치자들이나 권세들이나 만물이 다 그로 말미암고 그를 위하여 창조되었고","zh":"因为万有都是靠他造的，无论是天上的、地上的，能看见的、不能看见的，或是有位的、主治的、执政的、掌权的，一概都是借着他造的，又是为他造的。","es":"Porque en él fueron creadas todas las cosas, en los cielos y en la tierra, visibles e invisibles; sean tronos, sean dominios, sean principados, sean potestades; todo fue creado por medio de él y para él."}},
 "rom1_19":{"ref":{"en":"Romans 1:19–20","ko":"로마서 1:19–20","zh":"罗马书 1:19–20","es":"Romanos 1:19–20"},"t":{"en":"…because that which is known of God is revealed in them, for God revealed it to them. For the invisible things of him since the creation of the world are clearly seen, being perceived through the things that are made, even his everlasting power and divinity, so that they may be without excuse.","ko":"이는 하나님을 알 만한 것이 그들 속에 보임이라. 하나님께서 이를 그들에게 보이셨느니라. 창세로부터 그의 보이지 아니하는 것들 곧 그의 영원하신 능력과 신성이 그가 만드신 만물에 분명히 보여 알려졌나니 그러므로 그들이 핑계하지 못할지니라.","zh":"神的事情，人所能知道的，原显明在人心里，因为神已经给他们显明。自从造天地以来，神的永能和神性是明明可知的，虽是眼不能见，但借着所造之物就可以晓得，叫人无可推诿。","es":"…porque lo que de Dios se conoce les es manifiesto, pues Dios se lo manifestó. Porque las cosas invisibles de él, su eterno poder y deidad, se hacen claramente visibles desde la creación del mundo, siendo entendidas por medio de las cosas hechas; de modo que no tienen excusa."}},
 "heb1_3":{"ref":{"en":"Hebrews 1:3","ko":"히브리서 1:3","zh":"希伯来书 1:3","es":"Hebreos 1:3"},"t":{"en":"His Son is the radiance of his glory, the very image of his substance, and upholding all things by the word of his power.","ko":"이는 하나님의 영광의 광채시요 그 본체의 형상이시라. 그의 능력의 말씀으로 만물을 붙드시며","zh":"他是神荣耀所发的光辉，是神本体的真像，常用他权能的命令托住万有。","es":"El cual, siendo el resplandor de su gloria, y la imagen misma de su sustancia, y quien sustenta todas las cosas con la palabra de su poder."}},
 "heb11_3":{"ref":{"en":"Hebrews 11:3","ko":"히브리서 11:3","zh":"希伯来书 11:3","es":"Hebreos 11:3"},"t":{"en":"By faith we understand that the universe has been framed by the word of God, so that what is seen has not been made out of things which are visible.","ko":"믿음으로 모든 세계가 하나님의 말씀으로 지어진 줄을 우리가 아나니, 보이는 것은 나타난 것으로 말미암아 된 것이 아니니라.","zh":"我们因着信，就知道诸世界是借神的话造成的；这样，所看见的，并不是从显然之物造出来的。","es":"Por la fe entendemos haber sido constituido el universo por la palabra de Dios, de modo que lo que se ve fue hecho de lo que no se veía."}},
 "ps90_2":{"ref":{"en":"Psalm 90:2","ko":"시편 90:2","zh":"诗篇 90:2","es":"Salmo 90:2"},"t":{"en":"Before the mountains were born, before you had formed the earth and the world, even from everlasting to everlasting, you are God.","ko":"산이 생기기 전, 땅과 세계도 주께서 조성하시기 전 곧 영원부터 영원까지 주는 하나님이시니이다.","zh":"诸山未曾生出，地与世界你未曾造成，从亘古到永远，你是神。","es":"Antes que naciesen los montes y formases la tierra y el mundo, desde el siglo y hasta el siglo, tú eres Dios."}},
 "ex3_14":{"ref":{"en":"Exodus 3:14","ko":"출애굽기 3:14","zh":"出埃及记 3:14","es":"Éxodo 3:14"},"t":{"en":"God said to Moses, “I AM WHO I AM,” and he said, “You shall tell the children of Israel this: ‘I AM has sent me to you.’”","ko":"하나님이 모세에게 이르시되 “나는 스스로 있는 자이니라” 하시고 또 이르시되 “너는 이스라엘 자손에게 이같이 이르기를 ‘스스로 있는 자가 나를 너희에게 보내셨다’ 하라” 하시니라.","zh":"神对摩西说：“我是自有永有的。”又说：“你要对以色列人这样说：‘那自有的打发我到你们这里来。’”","es":"Y respondió Dios a Moisés: “YO SOY EL QUE SOY.” Y dijo: “Así dirás a los hijos de Israel: ‘YO SOY me envió a vosotros.’”"}},
 "1ti6_15":{"ref":{"en":"1 Timothy 6:15","ko":"디모데전서 6:15","zh":"提摩太前书 6:15","es":"1 Timoteo 6:15"},"t":{"en":"…the blessed and only Ruler, the King of kings, and Lord of lords.","ko":"하나님은 복되시고 유일하신 주권자이시요, 만왕의 왕이시며 만주의 주이시라.","zh":"那可称颂、独有权能的，万王之王、万主之主。","es":"…el bienaventurado y solo Soberano, Rey de reyes, y Señor de señores."}},
 "jn10_29":{"ref":{"en":"John 10:29","ko":"요한복음 10:29","zh":"约翰福音 10:29","es":"Juan 10:29"},"t":{"en":"My Father who has given them to me is greater than all. No one is able to snatch them out of my Father’s hand.","ko":"그들을 주신 내 아버지는 만물보다 크시매 아무도 아버지의 손에서 빼앗을 수 없느니라.","zh":"我父把羊赐给我，他比万有都大，谁也不能从我父手里把他们夺去。","es":"Mi Padre que me las dio, es mayor que todos, y nadie las puede arrebatar de la mano de mi Padre."}},
 "2ch6_18":{"ref":{"en":"2 Chronicles 6:18","ko":"역대하 6:18","zh":"历代志下 6:18","es":"2 Crónicas 6:18"},"t":{"en":"But will God indeed dwell with men on the earth? Behold, heaven and the heaven of heavens can’t contain you; how much less this house which I have built!","ko":"하나님이 참으로 사람과 함께 땅에 계시리이까? 보소서, 하늘과 하늘들의 하늘이라도 주를 용납하지 못하겠거든 하물며 내가 건축한 이 성전이오리이까!","zh":"神果真与世人同住在地上吗？看哪，天和天上的天尚且不足你居住的，何况我所建的这殿呢？","es":"Pero ¿es verdad que Dios habitará con el hombre en la tierra? He aquí, los cielos y los cielos de los cielos no te pueden contener; ¿cuánto menos esta casa que he edificado?"}},
 "gen1_6":{"ref":{"en":"Genesis 1:6–10","ko":"창세기 1:6–10","zh":"创世记 1:6–10","es":"Génesis 1:6–10"},"t":{"en":"God said, “Let there be an expanse in the middle of the waters, and let it divide the waters from the waters.” … God called the expanse “sky.” … God said, “Let the waters be gathered together to one place, and let the dry land appear,” and it was so. … God saw that it was good.","ko":"하나님이 이르시되 “물 가운데에 궁창이 있어 물과 물로 나뉘라” 하시고 … 하나님이 궁창을 하늘이라 부르시니라. … 하나님이 이르시되 “천하의 물이 한 곳으로 모이고 뭍이 드러나라” 하시니 그대로 되니라. … 하나님이 보시기에 좋았더라.","zh":"神说：“诸水之间要有空气，将水分为上下。”……神称空气为天。……神说：“天下的水要聚在一处，使旱地露出来。”事就这样成了。……神看着是好的。","es":"Dijo Dios: “Haya expansión en medio de las aguas, y separe las aguas de las aguas.” … Y llamó Dios a la expansión Cielos. … Dijo Dios: “Júntense las aguas en un lugar, y descúbrase lo seco,” y fue así. … Y vio Dios que era bueno."}},
 "2pe3_10":{"ref":{"en":"2 Peter 3:7, 10","ko":"베드로후서 3:7, 10","zh":"彼得后书 3:7、10","es":"2 Pedro 3:7, 10"},"t":{"en":"But the heavens that exist now and the earth, by the same word have been stored up for fire… But the day of the Lord will come as a thief, in which the heavens will pass away with a great noise, and the elements will be dissolved with fervent heat.","ko":"이제 하늘과 땅은 그 동일한 말씀으로 불사르기 위하여 보호하신 바 되어 … 주의 날이 도둑 같이 오리니 그 날에는 하늘이 큰 소리로 떠나가고 물질이 뜨거운 불에 풀어지리라.","zh":"但现在的天地还是凭着那命存留，直留到审判和沉沦的日子，用火焚烧。……主的日子要像贼来到一样。那日，天必大有响声废去，有形质的都要被烈火销化。","es":"Pero los cielos y la tierra que existen ahora, por la misma palabra están reservados para el fuego… Pero el día del Señor vendrá como ladrón; en el cual los cielos pasarán con grande estruendo, y los elementos ardiendo serán deshechos."}},
 "rev21_1":{"ref":{"en":"Revelation 21:1","ko":"요한계시록 21:1","zh":"启示录 21:1","es":"Apocalipsis 21:1"},"t":{"en":"I saw a new heaven and a new earth, for the first heaven and the first earth have passed away, and the sea is no more.","ko":"또 내가 새 하늘과 새 땅을 보니 처음 하늘과 처음 땅이 없어졌고 바다도 다시 있지 않더라.","zh":"我又看见一个新天新地，因为先前的天地已经过去了，海也不再有了。","es":"Vi un cielo nuevo y una tierra nueva; porque el primer cielo y la primera tierra pasaron, y el mar ya no existía más."}},
 "mt25_41":{"ref":{"en":"Matthew 25:41","ko":"마태복음 25:41","zh":"马太福音 25:41","es":"Mateo 25:41"},"t":{"en":"Then he will say… “Depart from me, you cursed, into the eternal fire which is prepared for the devil and his angels.”","ko":"그 때에 임금이 … 이르시되 “저주를 받은 자들아, 나를 떠나 마귀와 그 사자들을 위하여 예비된 영원한 불에 들어가라.”","zh":"王又要向那左边的说：“你们这被咒诅的人，离开我，进入那为魔鬼和他的使者所预备的永火里去。”","es":"Entonces dirá… “Apartaos de mí, malditos, al fuego eterno preparado para el diablo y sus ángeles.”"}},
 "rev20_14":{"ref":{"en":"Revelation 20:14–15","ko":"요한계시록 20:14–15","zh":"启示录 20:14–15","es":"Apocalipsis 20:14–15"},"t":{"en":"Death and Hades were thrown into the lake of fire. This is the second death, the lake of fire. If anyone was not found written in the book of life, he was thrown into the lake of fire.","ko":"사망과 음부도 불못에 던져지니 이것은 둘째 사망 곧 불못이라. 누구든지 생명책에 기록되지 못한 자는 불못에 던져지더라.","zh":"死亡和阴间也被扔在火湖里，这火湖就是第二次的死。若有人名字没记在生命册上，他就被扔在火湖里。","es":"Y la muerte y el Hades fueron lanzados al lago de fuego. Esta es la muerte segunda. Y el que no se halló inscrito en el libro de la vida fue lanzado al lago de fuego."}},
 "jn14_6":{"ref":{"en":"John 14:6","ko":"요한복음 14:6","zh":"约翰福音 14:6","es":"Juan 14:6"},"t":{"en":"Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me.”","ko":"예수께서 이르시되 “내가 곧 길이요 진리요 생명이니 나로 말미암지 않고는 아버지께로 올 자가 없느니라.”","zh":"耶稣说：“我就是道路、真理、生命；若不借着我，没有人能到父那里去。”","es":"Jesús le dijo: “Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.”"}},
 "heb11_1":{"ref":{"en":"Hebrews 11:1","ko":"히브리서 11:1","zh":"希伯来书 11:1","es":"Hebreos 11:1"},"t":{"en":"Now faith is assurance of things hoped for, proof of things not seen.","ko":"믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거니.","zh":"信就是所望之事的实底，是未见之事的确据。","es":"Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve."}}
},
"blocks":[
 {"t":"lesson","n":"1.1","title":{"en":"Two Worlds & Creation","ko":"두 세계와 창조","zh":"两个世界与创造","es":"Dos mundos y la creación"}},
 {"t":"p","x":{"en":"We come to know the world by seeing it. What our eyes confirm, we call real — and science has stretched our sight remarkably far. The telescope reaches out to galaxies billions of light-years away; the microscope reaches down to the cell, and to the atom. The world of the visible keeps growing.","ko":"우리는 세상을 봄으로써 알아 갑니다. 눈으로 확인한 것을 우리는 실재라 부르지요. 그리고 과학은 우리의 시야를 놀랍도록 넓혀 주었습니다. 망원경은 수십억 광년 떨어진 은하까지 닿고, 현미경은 세포와 원자에까지 이릅니다. 볼 수 있는 세계는 계속 커지고 있습니다.","zh":"我们靠观看来认识世界。眼睛所证实的，我们就称之为真实。而科学把我们的视野拓展得极其遥远：望远镜能望见数十亿光年之外的星系，显微镜能看到细胞，乃至原子。看得见的世界不断在扩大。","es":"Llegamos a conocer el mundo al verlo. Lo que nuestros ojos confirman, lo llamamos real, y la ciencia ha extendido nuestra vista de forma asombrosa: el telescopio alcanza galaxias a miles de millones de años luz; el microscopio llega hasta la célula y el átomo. El mundo de lo visible no deja de crecer."}},
 {"t":"p","x":{"en":"Yet the invisible world the Bible speaks of is not something farther away, or smaller, waiting for a stronger lens. It cannot be reached by the eyes at all — nor by any of the five senses — because it is spiritual.","ko":"그러나 이 성경이 말하는 보이지 않는 세계는, 더 멀리 있거나 더 작아서 더 좋은 렌즈를 기다리는 그런 것이 아닙니다. 그것은 눈으로는 결코 닿을 수 없으며, 나아가 오감 중 어느 것으로도 감지되지 않습니다. 왜냐하면 그것은 영적인 것입니다.","zh":"然而，这圣经所说的看不见的世界，并不是更远、更小、只等更好镜头去看的东西。它根本无法用眼睛触及，也无法被五官中的任何一种所感知，因为它是属灵的。","es":"Sin embargo, el mundo invisible del que habla la Biblia no es algo más lejano, ni más pequeño, que espere una lente mejor. No puede alcanzarse con los ojos —ni con ninguno de los cinco sentidos—, porque es espiritual."}},
 {"t":"p","x":{"en":"If something cannot be seen, or touched, or measured, does that alone prove it is not there?","ko":"보이지 않고, 만질 수 없고, 측정할 수 없다면 — 그것만으로 그것이 없다고 증명되는 것일까요?","zh":"如果一样东西看不见、摸不着、量不出，单凭这一点，就能证明它不存在吗？","es":"Si algo no puede verse, ni tocarse, ni medirse, ¿basta eso para probar que no existe?"}},

 {"t":"h","x":{"en":"Two worlds","ko":"두 세계","zh":"两个世界","es":"Dos mundos"}},
 {"t":"p","x":{"en":"People assume that what they can see is real, and what they cannot see is not. It is true that even the physical world hides much from our eyes — unseen forces, waves, the “dark energy” said to fill most of the cosmos. But all of that still belongs to the material world; it is unseen matter, not another world.","ko":"사람들은 보이는 것은 실재이고 보이지 않는 것은 아니라고 여깁니다. 물론 물질 세계에도 눈에 보이지 않는 것이 많습니다. 보이지 않는 힘들, 파동, 우주의 대부분을 채운다는 ‘암흑 에너지’ 같은 것 말입니다. 그러나 그것들은 여전히 물질 세계에 속합니다. 보이지 않는 ‘물질’일 뿐, 또 다른 세계가 아닙니다.","zh":"人们以为看得见的才是真实的，看不见的就不是。诚然，连物质世界也有许多是眼睛看不见的——看不见的力量、波动，以及据说充满宇宙大部分的“暗能量”。但这些仍属于物质世界，只是看不见的“物质”，并不是另一个世界。","es":"La gente supone que lo que se ve es real, y lo que no se ve, no lo es. Es cierto que aun el mundo físico esconde mucho de nuestros ojos: fuerzas invisibles, ondas, la “energía oscura” que, según se dice, llena la mayor parte del cosmos. Pero todo eso sigue perteneciendo al mundo material; es materia invisible, no otro mundo."}},
 {"t":"p","x":{"en":"There is another kind of unseen, though — one the five senses cannot reach at all. Standing before some overwhelming force of nature; the cold dread at the scene of a killing; a desperate prayer wrung out of us when all hope is gone; the terror before death itself — in such moments something stirs in us that no instrument can measure: awe, longing, the sense of a Presence greater than ourselves. Some have called it the numinous — the feeling of the holy. In every age and every culture, human beings have felt it, and have spoken of spirits, of the sacred, of the divine.","ko":"그런데 오감으로는 결코 닿을 수 없는 또 다른 종류의 ‘보이지 않음’이 있습니다. 거대한 대자연 현상 앞에 설 때, 살인현장에서의 오싹함, 너무나 절망적인 상황에서 간절한 기도, 그리고 죽음이라는 절망 앞에 어떤 기계로도 측정할 수 없는 무언가가 우리 안에서 일어납니다. 경외감, 그리움, 나보다 크신 어떤 임재의 느낌입니다. 어떤 이들은 이것을 ‘누미노제(거룩함의 감각)’라 불렀습니다. 모든 시대, 모든 문화의 사람들이 이것을 느꼈고, 영(靈)과 거룩함과 신적인 것에 대해 말해 왔습니다.","zh":"然而，还有另一种“看不见”，是五官根本无法触及的。当我们站在浩大的自然景象面前，在凶案现场感到的那股寒栗，在绝境中被逼出来的恳切祷告，面对死亡这一绝望之时——心中会涌起某种任何仪器都无法测量的东西：敬畏、渴慕、一种比自己更大的“临在”之感。有人称之为“神圣者的感受”（the numinous）。各个时代、各种文化的人都曾感受到它，并谈论灵、圣、以及神。","es":"Sin embargo, hay otro tipo de invisible, uno que los cinco sentidos no pueden alcanzar. Ante una fuerza inmensa de la naturaleza; el escalofrío en la escena de un asesinato; una oración desesperada que brota cuando ya no queda esperanza; el pavor ante la muerte misma — en esos momentos algo se mueve en nosotros que ningún instrumento puede medir: asombro, anhelo, la sensación de una Presencia mayor que nosotros. Algunos lo han llamado lo numinoso: el sentimiento de lo sagrado. En toda época y cultura, los seres humanos lo han sentido y han hablado de espíritus, de lo sagrado, de lo divino."}},
 {"t":"p","x":{"en":"Scripture names it plainly: there are two worlds — the visible, the physical world, and the invisible, the spiritual world. Our senses are limited, and not always reliable. Yet once we grant that a spiritual world may — even probably — exist, we can look closer, come to know, and at last believe. Science itself works this way: it forms a hypothesis about principles it cannot yet see, tests it, and finally proves it. This is not so different.","ko":"성경은 그것을 분명히 말합니다. 두 세계가 있습니다. 보이는 세계 곧 물질 세계와, 보이지 않는 세계 곧 영의 세계입니다. 우리의 감각은 제한되어 있고, 늘 신뢰할 수 있는 것도 아닙니다. 그러나 영의 세계가 존재할 수 있음을 — 아니, 충분히 그럴 법함을 — 인정한다면, 우리는 더 가까이 살펴 알아가고 마침내 믿을 수 있습니다. 사실 과학도 이렇게 일합니다. 아직 보지 못한 원리에 대해 가설을 세우고, 시험하고, 마침내 증명하지요. 이것도 크게 다르지 않습니다.","zh":"圣经把这说得明明白白：有两个世界——看得见的物质世界，和看不见的属灵世界。我们的感官有限，也并不总是可靠。然而，一旦承认属灵的世界可能存在——甚至很可能存在——我们就能更走近去考察、去认识，最终去相信。其实科学也是这样运作的：先对尚未看见的原理提出假设，加以试验，最终得以证明。这与信心并无太大不同。","es":"La Escritura lo dice con claridad: hay dos mundos — el visible, el mundo físico, y el invisible, el mundo espiritual. Nuestros sentidos son limitados, y no siempre fiables. Pero cuando admitimos que un mundo espiritual puede — incluso probablemente — existir, podemos mirar más de cerca, llegar a conocer y por fin creer. La ciencia misma funciona así: formula una hipótesis sobre principios que aún no ve, la pone a prueba y finalmente la demuestra. Esto no es tan distinto."}},
 {"t":"p","x":{"en":"And the Bible says more still: the things that are seen — the material — remain only for a time, while the things that are unseen — the spiritual — are eternal.","ko":"보이는 것 곧 물질적인 것은 한시적인 시간에 머무르지만, 보이지 않는 것 곧 영적인 것은 영원하다고 성경은 또 말합니다.","zh":"圣经还说：看得见的，就是物质的，只存留一时；看不见的，就是属灵的，却是永远的。","es":"Y la Biblia dice aún más: lo que se ve —lo material— permanece solo por un tiempo, mientras que lo que no se ve —lo espiritual— es eterno."}},
 {"t":"s","v":["col1_16","2co4_18"]},
 {"t":"h","x":{"en":"Created, or evolved?","ko":"창조인가, 진화인가?","zh":"是受造，还是进化？","es":"¿Creado o evolucionado?"}},
 {"t":"p","x":{"en":"How did everything begin? Two great theories answer: creation and evolution. Neither can be perfectly proven, for no one was present to watch the beginning of the universe or of life. And evolution's hardest problem remains unsolved — it cannot explain how living things ever arose from non-living matter.","ko":"모든 것은 어떻게 시작되었을까요? 두 가지 큰 이론이 답합니다. 창조와 진화입니다. 그러나 어느 쪽도 완벽히 증명될 수 없습니다. 우주와 생명의 시작을 지켜본 사람이 아무도 없기 때문입니다. 그리고 진화론의 가장 어려운 문제는 여전히 풀리지 않았습니다. 생명이 어떻게 무생물에서 생겨났는지 설명하지 못하는 것입니다.","zh":"万物是怎样开始的？有两大理论作答：创造与进化。但两者都无法被完全证明，因为没有人在场目睹宇宙和生命的起初。而进化论最难的问题至今仍未解决——它无法解释生命如何从无生命之物中产生。","es":"¿Cómo empezó todo? Dos grandes teorías responden: la creación y la evolución. Ninguna puede probarse por completo, pues nadie estuvo presente para ver el comienzo del universo ni de la vida. Y el problema más difícil de la evolución sigue sin resolverse: no puede explicar cómo lo vivo surgió de lo que no tiene vida."}},
 {"t":"p","x":{"en":"The Christian faith begins here: in the beginning God created all things. He spoke His Word, and all creation obeyed it. His unseen nature — His eternal power and divinity — is made plain through the things He has made, so that no one is without excuse.","ko":"기독교 신앙은 여기서 시작합니다. 태초에 하나님이 만물을 창조하셨다는 것입니다. 그가 말씀을 하시니 모든 피조물이 그 말씀에 순종했습니다. 그의 보이지 않는 본성 곧 영원하신 능력과 신성이 그가 지으신 만물을 통해 분명히 드러나므로, 아무도 핑계할 수 없습니다.","zh":"基督信仰从这里开始：起初，神创造了万物。他一说话，万有便顺服他的话。他那看不见的本性——永恒的大能和神性——借着他所造之物显明出来，叫人无可推诿。","es":"La fe cristiana comienza aquí: en el principio Dios creó todas las cosas. Habló su Palabra, y toda la creación la obedeció. Su naturaleza invisible —su eterno poder y divinidad— se hace evidente por medio de lo que ha hecho, de modo que nadie tiene excusa."}},
 {"t":"s","v":["rom1_19","heb1_3"]},
 {"t":"dia","kind":"cmp","title":{"en":"Science and Scripture — not rivals","ko":"과학과 성경 — 경쟁자가 아니다","zh":"科学与圣经 — 并非对手","es":"La ciencia y la Escritura — no son rivales"},
  "heads":[{"b":{"en":"Science","ko":"과학","zh":"科学","es":"La ciencia"},"s":{"en":"a tool of discovery","ko":"발견의 도구","zh":"发现的工具","es":"herramienta de descubrimiento"}},
           {"b":{"en":"Scripture","ko":"성경","zh":"圣经","es":"La Escritura"},"s":{"en":"the ground of faith","ko":"믿음의 기초","zh":"信心的根基","es":"el fundamento de la fe"}}],
  "rows":[
   {"label":{"en":"It answers","ko":"답하는 것","zh":"回答的是","es":"Responde a"},"l":{"en":"How things work","ko":"어떻게 작동하는가","zh":"事物如何运作","es":"Cómo funcionan las cosas"},"r":{"en":"Who made them, and why","ko":"누가, 왜 만들었는가","zh":"是谁所造，为何而造","es":"Quién las hizo, y por qué"}},
   {"label":{"en":"It reaches","ko":"닿는 범위","zh":"所及范围","es":"Alcanza"},"l":{"en":"The visible","ko":"보이는 것","zh":"看得见的","es":"Lo visible"},"r":{"en":"Beyond the visible, by faith","ko":"믿음으로 보이는 것 너머","zh":"凭信心达到看不见之处","es":"Más allá de lo visible, por la fe"}}
  ]},
 {"t":"callout","x":{"en":"Science shows how things work; Scripture tells us who made them, and why. Faith is the power that reaches past what science can see — for by faith we understand that the worlds were framed by the word of God.","ko":"과학은 사물이 어떻게 작동하는지 보여 주고, 성경은 누가 왜 만들었는지 말해 줍니다. 믿음은 과학이 볼 수 있는 것 너머에 닿는 능력입니다. 믿음으로 우리는 모든 세계가 하나님의 말씀으로 지어진 줄을 압니다.","zh":"科学显明事物如何运作，圣经告诉我们是谁所造、为何而造。信心是超越科学所能看见之处的能力——因着信，我们知道诸世界是借神的话造成的。","es":"La ciencia muestra cómo funcionan las cosas; la Escritura dice quién las hizo, y por qué. La fe es el poder que alcanza más allá de lo que la ciencia ve, pues por la fe entendemos que los mundos fueron formados por la palabra de Dios."}},
 {"t":"s","v":["heb11_3"]},

 {"t":"q","items":[
  {"en":"Name something invisible that you are sure exists. How much do you rely on your senses — and are they always reliable?","ko":"보이지 않지만 분명히 존재한다고 확신하는 것을 하나 말해 보십시오. 나는 내 감각에 얼마나 의존하며, 그 감각은 늘 신뢰할 만합니까?","zh":"说出一样看不见却你确信存在的东西。你有多依赖自己的感官？它们总是可靠的吗？","es":"Menciona algo invisible que estés seguro de que existe. ¿Cuánto dependes de tus sentidos, y son siempre fiables?"},
  {"en":"What are your views on science and the Bible? Do you see them as alike, or in conflict — and how do you explain it?","ko":"과학과 성경에 대한 나의 생각은 어떠합니까? 둘을 비슷하다고 봅니까, 아니면 서로 충돌한다고 봅니까? 그것을 어떻게 설명하시겠습니까?","zh":"你如何看待科学与圣经？你觉得二者相近，还是彼此冲突？你如何解释？","es":"¿Qué piensas de la ciencia y la Biblia? ¿Las ves parecidas o en conflicto? ¿Cómo lo explicas?"}
 ]},
 {"t":"lesson","n":"1.2","title":{"en":"Who is God?","ko":"하나님은 누구신가","zh":"神是谁","es":"¿Quién es Dios?"}},
 {"t":"h","x":{"en":"Who is God?","ko":"하나님은 누구신가?","zh":"神是谁？","es":"¿Quién es Dios?"}},
 {"t":"p","x":{"en":"If it is God who made both worlds, we must ask who He is. Scripture answers that there is no one like Him: He is above time and space, He created all things and stands over them, and He alone is God.","ko":"두 세계를 모두 지으신 분이 하나님이라면, 우리는 그가 누구신지 물어야 합니다. 성경은 그와 같은 이가 없다고 답합니다. 그는 시간과 공간을 초월하시고, 만물을 창조하시어 그 위에 계시며, 오직 그만이 홀로 하나님이십니다.","zh":"既然造了两个世界的是神，我们就当问他是谁。圣经的回答是：没有一位像他。他超越时间与空间，创造万有并在万有之上，唯有他是独一的神。","es":"Si es Dios quien hizo ambos mundos, debemos preguntar quién es. La Escritura responde que no hay nadie como Él: está por encima del tiempo y del espacio, creó todas las cosas y está sobre ellas, y solo Él es Dios."}},
 {"t":"dia","kind":"grid","title":{"en":"Who God is","ko":"하나님은 어떤 분이신가","zh":"神是怎样的","es":"Quién es Dios"},
  "items":[
   {"b":{"en":"Eternal","ko":"영원하심","zh":"永恒","es":"Eterno"},"s":{"en":"From everlasting to everlasting — no beginning and no end. In Him there is no time.","ko":"영원부터 영원까지 — 시작도 끝도 없으십니다. 그 안에는 시간이 없습니다.","zh":"从亘古到永远——无始无终。在他里面没有时间。","es":"Desde el siglo y hasta el siglo: sin principio ni fin. En Él no hay tiempo."},"e":{"en":"Psalm 90:2","ko":"시편 90:2","zh":"诗篇 90:2","es":"Salmo 90:2"}},
   {"b":{"en":"Self-existent","ko":"스스로 계심","zh":"自有永有","es":"Existe por sí mismo"},"s":{"en":"He was made by no one. He alone is the Uncreated; everything else is created.","ko":"아무에게도 지음받지 않으셨습니다. 오직 그만이 스스로 계신 분이시며, 그 밖의 모든 것은 피조물입니다.","zh":"不被任何人所造。唯有他是非受造的，其余一切都是受造之物。","es":"Nadie lo hizo. Solo Él es el Increado; todo lo demás es creado."},"e":{"en":"Exodus 3:14","ko":"출애굽기 3:14","zh":"出埃及记 3:14","es":"Éxodo 3:14"}},
   {"b":{"en":"The only Ruler","ko":"유일한 주권자","zh":"独一的主宰","es":"El único Soberano"},"s":{"en":"The blessed and only Ruler, King of kings. He reigns over all and lacks nothing.","ko":"복되시고 유일하신 주권자, 만왕의 왕이십니다. 만물을 다스리시며 부족함이 없으십니다.","zh":"那可称颂、独有权能的，万王之王。他统管万有，一无所缺。","es":"El bienaventurado y único Soberano, Rey de reyes. Reina sobre todo y nada le falta."},"e":{"en":"1 Timothy 6:15","ko":"디모데전서 6:15","zh":"提摩太前书 6:15","es":"1 Timoteo 6:15"}},
   {"b":{"en":"Greater than all","ko":"만물보다 크심","zh":"超乎万有","es":"Mayor que todo"},"s":{"en":"Greater than everything He has made; the highest heavens cannot contain Him.","ko":"그가 지으신 모든 것보다 크시며, 하늘들의 하늘이라도 그를 담을 수 없습니다.","zh":"比他所造的一切都大；诸天的天尚且不能容纳他。","es":"Mayor que todo lo que ha hecho; ni los cielos de los cielos pueden contenerlo."},"e":{"en":"John 10:29 · 2 Chr 6:18","ko":"요 10:29 · 대하 6:18","zh":"约 10:29 · 代下 6:18","es":"Jn 10:29 · 2 Cr 6:18"}}
  ]},
 {"t":"s","v":["ps90_2","ex3_14","1ti6_15","jn10_29"]},
 {"t":"dia","kind":"cmp","title":{"en":"“In the beginning” — two beginnings","ko":"“태초에” — 두 개의 시작","zh":"“起初” — 两个开端","es":"“En el principio” — dos comienzos"},
  "heads":[{"b":{"en":"Genesis 1:1","ko":"창세기 1:1","zh":"创世记 1:1","es":"Génesis 1:1"},"s":{"en":"the beginning of time","ko":"시간의 시작","zh":"时间的开始","es":"el comienzo del tiempo"}},
           {"b":{"en":"John 1:1","ko":"요한복음 1:1","zh":"约翰福音 1:1","es":"Juan 1:1"},"s":{"en":"eternity, before time","ko":"시간 이전의 영원","zh":"时间之前的永恒","es":"la eternidad, antes del tiempo"}}],
  "rows":[
   {"l":{"en":"When the world was made — the start of all time.","ko":"세상이 지어진 때 — 모든 시간의 시작.","zh":"世界被造之时——一切时间的开端。","es":"Cuando el mundo fue hecho: el inicio de todo el tiempo."},"r":{"en":"The Word who already was — existing beyond time.","ko":"이미 계시던 말씀 — 시간을 초월해 존재하심.","zh":"那已经存在的道——超越时间而存在。","es":"El Verbo que ya era: existiendo más allá del tiempo."}}
  ]},

 {"t":"q","items":[
  {"en":"Can you imagine having no sense of time at all — no beginning and no end? What might it be to exist in eternity?","ko":"시간이라는 개념이 전혀 없다면 — 시작도 끝도 없다면 — 어떤 느낌일지 상상해 보십시오. 영원 속에 있다는 것은 어떤 것일까요?","zh":"试想若完全没有时间的概念——没有开始，也没有结束——那会是怎样？置身于永恒之中，又会是如何？","es":"Imagina no tener ninguna noción del tiempo —sin principio ni fin—. ¿Cómo sería existir en la eternidad?"},
  {"en":"If God lacks nothing and needs nothing, why would He make the world — and make you? How does knowing who God is change how you see yourself, and how you come to Him?","ko":"하나님이 부족함도, 필요도 없으시다면, 왜 세상을 지으시고 — 또 나를 지으셨을까요? 하나님이 어떤 분이신지 아는 것은, 내가 나 자신을 보는 방식과 그분께 나아가는 태도를 어떻게 바꿉니까?","zh":"神既一无所缺、一无所需，为何还要造世界——又造你我？认识神是谁，如何改变你看待自己、以及你来到他面前的方式？","es":"Si a Dios nada le falta y nada necesita, ¿por qué haría el mundo, y por qué te haría a ti? ¿Cómo cambia el saber quién es Dios tu manera de verte y de acercarte a Él?"}
 ]},
 {"t":"lesson","n":"1.3","title":{"en":"The Heavens","ko":"하늘","zh":"诸天","es":"Los cielos"}},
 {"t":"h","x":{"en":"The heavens","ko":"하늘","zh":"诸天","es":"Los cielos"}},
 {"t":"p","x":{"en":"If we believe, Scripture says, we may enter heaven. But where is this heaven? Just as there are two worlds, there are two heavens: the material heaven — the universe — and the spiritual heaven, which the Bible calls “the kingdom of heaven.”","ko":"성경은 우리가 믿으면 하늘에 들어갈 수 있다고 말합니다. 그런데 이 ‘하늘’은 어디에 있을까요? 두 세계가 있듯이, 하늘도 둘입니다. 물질의 하늘 곧 우주와, 성경이 ‘하늘나라’라 부르는 영의 하늘입니다.","zh":"圣经说，我们若相信，就能进入天堂。可这“天”在哪里呢？正如有两个世界，也有两重天：物质的天——宇宙，和圣经所称“天国”的属灵的天。","es":"Si creemos, dice la Escritura, podremos entrar en el cielo. Pero ¿dónde está ese cielo? Así como hay dos mundos, hay dos cielos: el cielo material —el universo— y el cielo espiritual, al que la Biblia llama “el reino de los cielos.”"}},
 {"t":"s","v":["2ch6_18"]},
 {"t":"p","x":{"en":"The spiritual heaven lies outside the material universe. Though invisible, it is still finite — for it too is God's creation; in fact it was His very first. It was made for the Son. There stands the throne of God, where Jesus serves the Father as our High Priest.","ko":"영의 하늘은 물질의 우주 바깥에 있습니다. 보이지 않지만 그것 역시 유한합니다. 그것도 하나님의 피조물이며, 사실 그의 첫 번째 창조물입니다. 그것은 아들을 위하여 지어졌습니다. 거기에 하나님의 보좌가 있고, 예수께서 우리의 대제사장으로서 아버지를 섬기십니다.","zh":"属灵的天在物质宇宙之外。它虽看不见，却仍是有限的——因为它也是神的创造，事实上是他最先的创造。它是为圣子而造的。神的宝座在那里，耶稣作我们的大祭司在那里事奉父。","es":"El cielo espiritual está fuera del universo material. Aunque invisible, es finito, pues también es creación de Dios; de hecho, fue lo primero que creó. Fue hecho para el Hijo. Allí está el trono de Dios, donde Jesús sirve al Padre como nuestro Sumo Sacerdote."}},
 {"t":"dia","kind":"tiers","title":{"en":"Three heavens","ko":"세 하늘","zh":"三重天","es":"Tres cielos"},
  "items":[
   {"n":{"en":"1st","ko":"첫째","zh":"第一重","es":"1.º"},"b":{"en":"The sky","ko":"하늘 (공중)","zh":"天空","es":"El cielo"},"s":{"en":"the air within the atmosphere","ko":"대기권 안의 하늘","zh":"大气层之内的天","es":"el aire dentro de la atmósfera"}},
   {"n":{"en":"2nd","ko":"둘째","zh":"第二重","es":"2.º"},"b":{"en":"The universe","ko":"우주","zh":"宇宙","es":"El universo"},"s":{"en":"the expanse — the material heaven","ko":"궁창 — 물질의 하늘","zh":"穹苍——物质的天","es":"la expansión — el cielo material"}},
   {"n":{"en":"3rd","ko":"셋째","zh":"第三重","es":"3.º"},"b":{"en":"The spiritual heaven","ko":"영의 하늘","zh":"属灵的天","es":"El cielo espiritual"},"s":{"en":"the kingdom of heaven, the throne of God","ko":"하늘나라, 하나님의 보좌","zh":"天国，神的宝座","es":"el reino de los cielos, el trono de Dios"}}
  ]},
 {"t":"p","x":{"en":"Genesis 1 describes how God made the visible world. He commanded the waters to divide and set an expanse between them — the universe, “wrapped” with water. Then He gathered the waters below, and dry land appeared. And He saw that it was good.","ko":"창세기 1장은 하나님이 어떻게 보이는 세계를 지으셨는지 이야기합니다. 그는 물을 나누라 명하시고 그 사이에 궁창을 두셨습니다. 바로 물로 ‘둘러싸인’ 우주입니다. 그런 다음 아래의 물을 한 곳에 모으시니 뭍이 드러났습니다. 그리고 보시기에 좋았습니다.","zh":"创世记第一章述说神如何造出看得见的世界。他命令诸水分开，在其间设立穹苍——就是被水“包裹”的宇宙。然后他聚集下面的水，旱地便露出来。神看着是好的。","es":"Génesis 1 describe cómo Dios hizo el mundo visible. Mandó que las aguas se separaran y puso una expansión entre ellas —el universo, “envuelto” en agua—. Luego reunió las aguas de abajo, y apareció lo seco. Y vio que era bueno."}},
 {"t":"s","v":["gen1_6"]},

 {"t":"q","items":[
  {"en":"How does learning where heaven is — and what will one day become of this universe — change the way you think about God's plans, and about your own life?","ko":"하늘이 어디에 있는지, 그리고 이 우주가 언젠가 어떻게 될지를 아는 것은, 하나님의 계획과 나 자신의 삶을 생각하는 방식을 어떻게 바꿉니까?","zh":"认识天在哪里、以及这宇宙有一天会有怎样的结局，如何改变你对神的计划、以及对自己人生的思考？","es":"Saber dónde está el cielo —y qué será un día de este universo— ¿cómo cambia tu manera de pensar en los planes de Dios y en tu propia vida?"},
  {"en":"Genesis pictures God setting the universe like an expanse between the waters, with a boundary. What does it mean to you that the universe is finite — that it had a beginning, and will have an end?","ko":"창세기는 하나님이 물 사이에 궁창을 두시듯 우주를 만드시고 경계를 정하셨다고 그립니다. 우주가 유한하다는 것 — 시작이 있었고 끝이 있으리라는 것 — 은 나에게 무엇을 의미합니까?","zh":"创世记描绘神像在水与水之间设立穹苍一样造出宇宙，并定了界限。宇宙是有限的——有开始、也将有结束——这对你意味着什么？","es":"Génesis describe a Dios formando el universo como una expansión entre las aguas, con un límite. ¿Qué significa para ti que el universo sea finito, que tuvo principio y tendrá fin?"}
 ]},
 {"t":"lesson","n":"1.4","title":{"en":"The End of the World","ko":"세상의 끝","zh":"世界的终结","es":"El fin del mundo"}},
 {"t":"h","x":{"en":"The end of the world","ko":"세상의 끝","zh":"世界的终结","es":"El fin del mundo"}},
 {"t":"p","x":{"en":"Scripture says a day is coming when heaven and earth will pass away, and this universe will become a lake of fire. By the same Word that made it, God will one day burn it up; until then, the world is being kept for the day of judgment.","ko":"성경은 하늘과 땅이 사라질 날이 오며, 이 우주가 불못이 되리라고 말합니다. 그것을 지으신 바로 그 말씀으로, 하나님은 언젠가 그것을 불사르실 것입니다. 그때까지 이 세상은 심판의 날을 위해 보존되고 있습니다.","zh":"圣经说，有一天天地都要过去，这宇宙要变成火湖。神必用当初造它的同一句话，将它焚烧；在此之前，世界被存留，直到审判的日子。","es":"La Escritura dice que vendrá un día en que el cielo y la tierra pasarán, y este universo se volverá un lago de fuego. Por la misma Palabra que lo hizo, Dios un día lo quemará; hasta entonces, el mundo es guardado para el día del juicio."}},
 {"t":"s","v":["2pe3_10","rev21_1"]},
 {"t":"p","x":{"en":"God did not make hell for people. It is the place prepared for the devil and his angels — and for those who refuse Jesus and follow the devil instead, whose names are not written in the book of life. The kingdom of God, by contrast, has no darkness, sickness, lack, suffering, or death — forever.","ko":"하나님은 사람을 위해 지옥을 만드신 것이 아닙니다. 그곳은 마귀와 그의 사자들을 위해 예비된 곳입니다. 그리고 예수를 거부하고 도리어 마귀를 따르는 자들, 곧 생명책에 이름이 기록되지 못한 자들을 위한 곳입니다. 반면 하나님의 나라에는 어둠도, 질병도, 결핍도, 고통도, 죽음도 영원히 없습니다.","zh":"神造地狱并不是为了人。那是为魔鬼和他的使者所预备的地方——也是为那些拒绝耶稣、反倒跟随魔鬼、名字没有记在生命册上的人所预备的。相反，神的国里永远没有黑暗、疾病、缺乏、痛苦或死亡。","es":"Dios no hizo el infierno para las personas. Es el lugar preparado para el diablo y sus ángeles —y para quienes rechazan a Jesús y siguen al diablo, cuyos nombres no están escritos en el libro de la vida—. El reino de Dios, en cambio, no tiene tinieblas, enfermedad, carencia, sufrimiento ni muerte, para siempre."}},
 {"t":"dia","kind":"fork",
  "stem":{"en":"One day this present universe will pass away — and every person arrives at one of two ends.","ko":"언젠가 이 우주는 사라지고 — 모든 사람은 두 결말 중 하나에 이릅니다.","zh":"有一天这宇宙将要过去——每个人都归于两种结局之一。","es":"Un día este universo pasará, y cada persona llega a uno de dos finales."},
  "items":[
   {"b":{"en":"The lake of fire","ko":"불못","zh":"火湖","es":"El lago de fuego"},"s":{"en":"Prepared for the devil and his angels, and all whose names are not in the book of life. The fire is never quenched.","ko":"마귀와 그 사자들, 그리고 생명책에 이름이 없는 모든 자를 위해 예비된 곳. 그 불은 결코 꺼지지 않습니다.","zh":"为魔鬼和他的使者，以及一切名字不在生命册上的人所预备。那火永不熄灭。","es":"Preparado para el diablo y sus ángeles, y para todos cuyos nombres no están en el libro de la vida. El fuego nunca se apaga."},"e":{"en":"Matthew 25:41 · Revelation 20:14–15","ko":"마태복음 25:41 · 요한계시록 20:14–15","zh":"马太福音 25:41 · 启示录 20:14–15","es":"Mateo 25:41 · Apocalipsis 20:14–15"}},
   {"b":{"en":"The kingdom of heaven","ko":"하늘나라","zh":"天国","es":"El reino de los cielos"},"s":{"en":"No darkness, no death — to live joyfully and forever with God. Entered through Jesus, the way, the truth, and the life.","ko":"어둠도 죽음도 없이 — 하나님과 함께 기쁘게 영원히 사는 곳. 길이요 진리요 생명이신 예수를 통해 들어갑니다.","zh":"没有黑暗，没有死亡——与神一同喜乐地永远活着。借着道路、真理、生命的耶稣进入。","es":"Sin tinieblas ni muerte: vivir con gozo y para siempre con Dios. Se entra por Jesús, el camino, la verdad y la vida."},"e":{"en":"John 14:6 · Revelation 21:1","ko":"요한복음 14:6 · 요한계시록 21:1","zh":"约翰福音 14:6 · 启示录 21:1","es":"Juan 14:6 · Apocalipsis 21:1"}}
  ]},
 {"t":"s","v":["mt25_41","rev20_14","jn14_6"]},
 {"t":"p","x":{"en":"We have not seen heaven or hell — and yet, by faith, we can be certain they are real. If we set our hearts to enter the eternal heaven and to live there with God, then nothing in this world matters more than this.","ko":"우리는 하늘도 지옥도 본 적이 없습니다. 그러나 믿음으로 우리는 그것들이 실재함을 확신할 수 있습니다. 우리가 영원한 하늘에 들어가 하나님과 함께 살기로 마음을 정한다면, 이 세상 그 무엇도 이보다 더 중요하지 않습니다.","zh":"我们从未见过天堂或地狱——然而凭着信心，我们可以确信它们是真实的。我们若立定心志要进入永恒的天，与神一同居住，那么世上再没有什么比这更重要。","es":"No hemos visto el cielo ni el infierno; y, sin embargo, por la fe podemos estar seguros de que son reales. Si ponemos el corazón en entrar en el cielo eterno y vivir allí con Dios, nada en este mundo importa más que esto."}},
 {"t":"mem","ref":"heb11_1"},
 {"t":"q","items":[
  {"en":"If this present universe will one day pass away, what changes about the priorities of your life today?","ko":"이 우주가 언젠가 사라질 것이라면, 오늘 내 삶의 우선순위에서 무엇이 달라져야 합니까?","zh":"如果这宇宙有一天要过去，你今天生活的优先次序该有什么改变？","es":"Si este universo un día pasará, ¿qué cambia en las prioridades de tu vida hoy?"},
  {"en":"You have not seen heaven or hell, yet by faith you can be sure they are real. How can you live each day preparing to enter the kingdom of heaven?","ko":"하늘도 지옥도 본 적 없지만, 믿음으로 그것들이 실재함을 확신할 수 있습니다. 하늘나라에 들어갈 것을 준비하며 나는 매일을 어떻게 살 수 있습니까?","zh":"你未曾见过天堂或地狱，却能凭信心确信它们是真实的。你如何能每天为进入天国而预备地活着？","es":"No has visto el cielo ni el infierno, y sin embargo por la fe puedes estar seguro de que son reales. ¿Cómo puedes vivir cada día preparándote para entrar en el reino de los cielos?"}
 ]}
]
};
